Fix sync commitee endpoint
prysmaticlabs/prysm pull request #10015
Opened 2021-12-14 18:39 UTC by potuz

In the back and forth to #9945 a bug was introduced in the logic to request future sync committees. This fixes that.

2021-12-14 18:53 UTC, rkapka requested changes
This fix needs a test.

2021-12-14 18:53 UTC, rkapka commented on beacon-chain/rpc/eth/beacon/sync_committee.go
> +		if reqPeriodStartEpoch > currentPeriodStartEpoch {
If someone requests more than 1 epoch into the future, I think it would be better to return an error rather than give them the next epoch's data.

2021-12-18 15:34 UTC, potuz commented
> This fix needs a test.

Added a fix for the test, I am wondering if it's better to modify the Mock StateFetcher to include an arbitrary expected state id as is the case of this test

2021-12-18 16:04 UTC, rkapka approved these changes

2021-12-18 16:04 UTC, merged