Move ErrNilValidatorsInState from one in each state version to a common one
prysmaticlabs/prysm pull request #10074
Opened 2022-01-12 06:27 UTC by leolara

**What type of PR is this?**
Refactor #10047 

**What does this PR do? Why is it needed?**

To increase DRY and enable DRY in tests and other users of the Beacon Chain state package,
an error that was duplicated unnecessarily in each version of the state is moved to the root
Beacon Chain state package.

**Which issues(s) does this PR fix?**

Related 

**Other notes for review**

None

2022-01-12 11:24 UTC, nisdas submitted a review, later dismissed
LGTM

2022-01-12 13:47 UTC, nisdas commented
This PR is blocked till #10069 is merged in as that PR will be applying a few non trivial changes to the state package and this PR
will conflict with it.

2022-01-12 14:57 UTC, prestonvanloon reviewed
Nice! LGTM

2022-01-13 11:28 UTC, rkapka commented
Even though #10069 was merged, let's wait for #9820

2022-01-13 11:30 UTC, nisdas commented
> Even though #10069 was merged, let's wait for #9820

This is a minor change, with the large changes having been added in #10069. #9820 will take a while to be fully merged in, we shouldn't do a complete block.

2022-01-13 16:15 UTC, rkapka commented
You are right. Let's at least make me and you required reviewers for any PR that touches state, like we discussed on Discord.

2022-01-14 01:32 UTC, leolara commented
Ok, so does that mean this can be merged? @rkapka @nisdas

2022-01-14 07:25 UTC, rkapka requested changes
We need the same changes applied to code inside `/state/state-native`.

2022-01-15 03:58 UTC, leolara commented
@rkapka  In the base branch (develop) there is no state/state-native, so is this still blocked? Or perhaps I do not understand your instructions?

2022-01-15 04:06 UTC, nisdas commented
Hey  @leolara , @rkapka should be referring to this directory: 
https://github.com/prysmaticlabs/prysm/tree/develop/beacon-chain/state/state-native

You will have to repeat what was done in this sub-package too, sorry for the inconvenience. This is a temporary thing until we fully roll out our feature.

2022-01-15 04:08 UTC, leolara commented
@nisdas Thanks 🤦 my bad

2022-01-15 11:56 UTC, rkapka commented
I apologize for the confusion

2022-01-18 03:45 UTC, leolara commented
@rkapka @nisdas please check again, state-native included

2022-01-18 07:20 UTC, nisdas approved these changes
Thanks for adding it in @leolara ! LGTM 

cc @rkapka

2022-01-18 07:35 UTC, rkapka submitted a review, later dismissed

2022-01-18 08:04 UTC, nisdas approved these changes

2022-01-18 08:08 UTC, leolara commented
@nisdas could you merge? I don't have the rights

2022-01-18 08:09 UTC, nisdas commented
@leolara Our CI is still running the build, it will take 10 -15 minutes more to be merged in.

2022-01-18 08:19 UTC, merged