Ignore topics when in optimistic mode
prysmaticlabs/prysm pull request #10274
Opened 2022-02-23 06:40 UTC by jmozah

This PR implements ignoring topic messages when in optimistic mode. Only `blocks` topic is kept open.

2022-02-23 16:34 UTC, terencechain reviewed
Let's target this for `develop` after https://github.com/prysmaticlabs/prysm/pull/10276 is merged

2022-02-23 17:18 UTC, prestonvanloon commented on beacon-chain/sync/validate_aggregate_proof_test.go
> +	_ = err
```suggestion
	assert.NoError(t, err)
```

2022-02-23 17:19 UTC, prestonvanloon commented on beacon-chain/sync/validate_attester_slashing_test.go
> +	_ = err
```suggestion
	assert.NoError(t, err)
```

2022-02-23 17:20 UTC, prestonvanloon requested changes
Please handle errors in test

2022-02-23 17:20 UTC, prestonvanloon commented on beacon-chain/sync/validate_beacon_attestation_test.go
> +	_ = err
```suggestion
	assert.NoError(t, err)
```

2022-02-23 17:20 UTC, prestonvanloon commented on beacon-chain/sync/validate_proposer_slashing_test.go
> +	_ = err
```suggestion
	assert.NoError(t, err)
```

2022-02-23 17:20 UTC, prestonvanloon commented on beacon-chain/sync/validate_voluntary_exit_test.go
> +	_ = err
```suggestion
	assert.NoError(t, err)
```

2022-02-24 07:34 UTC, nisdas reviewed
```go
	// We should not attempt to process this message if the node is running in optimistic mode.
	// We just ignore in p2p so that the peer is not penalized.
	status, err := s.cfg.chain.IsOptimistic(ctx)
	if err != nil {
		return pubsub.ValidationReject, nil
	}
	if status {
		return pubsub.ValidationIgnore, nil
	}
```

This is basically used in all the message handlers, this can be abstracted to a separate method and then used in all our gossip handlers.

2022-02-24 07:34 UTC, nisdas commented on beacon-chain/sync/validate_aggregate_proof.go
> +		return pubsub.ValidationReject, nil
you should return the error here, we have gossip message handler which will log errors for rejected messages. So we make sure that any errors are correctly bubbled up.

2022-02-28 22:21 UTC, terencechain commented
hi @jmozah could you fix the diffs, please?

2022-03-04 07:14 UTC, jmozah commented
Closing in favour of https://github.com/prysmaticlabs/prysm/pull/10300

2022-03-04 07:14 UTC, closed without merging