Some improvements for the state package testing
prysmaticlabs/prysm pull request #10316
Opened 2022-03-07 16:19 UTC by leolara

**What type of PR is this?**

Refactor

**What does this PR do? Why is it needed?**

Avoids some code repetition in the state package testing

**Which issues(s) does this PR fix?**

Related #10047

**Other notes for review**

2022-03-07 17:11 UTC, leolara commented on beacon-chain/state/testing/getters_block.go
> +func VerifyBeaconState_LatestBlockHeader(
I am just copying what is the name of the original test: `TestBeaconState_LatestBlockHeader`

2022-03-07 17:17 UTC, terencechain commented on beacon-chain/state/testing/getters_block.go
> +func VerifyBeaconState_LatestBlockHeader(
Then I think camel case is preferred since this is no longer an executable test rather than a test only helper function

2022-03-08 09:05 UTC, leolara commented
@terencechain please, check new commit

2022-03-10 09:34 UTC, rkapka requested changes
Please also add `state-native/v2/references_test.go` and `state-native/v3/references_test.go`

2022-03-10 10:18 UTC, leolara commented
@rkapka done

2022-03-10 11:35 UTC, rkapka approved these changes

2022-03-10 11:36 UTC, rkapka commented
Thanks! Let's wait for @terencechain's approval before merging

2022-03-10 11:42 UTC, rkapka commented
`bazel run //:gazelle -- fix` needed

2022-03-10 17:02 UTC, rkapka submitted a review, later dismissed

2022-03-10 21:54 UTC, rkapka commented
Hey @leolara , I just checked https://github.com/prysmaticlabs/prysm/pull/10316/commits/daaa2f9f2101c30667487cea2d3af1d926a6a3b6 and I'm pretty sure what @terencechain meant was to change `VerifyBeaconState_LatestBlockHeader` to `verifyBeaconStateLatestBlockHeader`, nothing else

2022-03-15 18:16 UTC, rkapka commented
Thanks for explaining. This looks good to me.

2022-03-15 18:16 UTC, rkapka approved these changes

2022-03-15 18:32 UTC, merged