remove optimistic control flag
prysmaticlabs/prysm pull request #10340
Opened 2022-03-10 20:24 UTC by potuz

This PR removes the `optimistic` parameter to fork-choices `ProcessBlock`, removing thus a boolean control flag and making it responsibility of the caller to specify when a block has been fully validated. By default, a block inserted to fork choice is considered optimistic.

2022-03-11 04:15 UTC, terencechain requested changes
I think it's a flawed UX to assume callers are aware that blocks get passed to `insertBlockToForkChoiceStore` and fork choice's `ProcessBlock` are default to optimistic. Callers could easily miss such implementation detail due to
- No additional comments specify this
- Function names don't specifying this

We should have twin functions like `ProcessOptimisticBlock` and `ProcessValidatedBlock` where the deduplication is addressed underneath the underlying function.

A good example of this is `ExecuteStateTransition` and `ExecuteStateTransitionNoVerifyAnySig`

2022-03-11 09:15 UTC, potuz commented
> I think it's a flawed UX to assume callers are aware that blocks get passed to `insertBlockToForkChoiceStore` and fork choice's `ProcessBlock` are default to optimistic. Callers could easily miss such implementation detail due to
> 
> * No additional comments specify this
> * Function names don't specifying this
> 
> We should have twin functions like `ProcessOptimisticBlock` and `ProcessValidatedBlock` where the deduplication is addressed underneath the underlying function.
> 
> A good example of this is `ExecuteStateTransition` and `ExecuteStateTransitionNoVerifyAnySig`



> I think it's a flawed UX to assume callers are aware that blocks get passed to `insertBlockToForkChoiceStore` and fork choice's `ProcessBlock` are default to optimistic. Callers could easily miss such implementation detail due to
> 
> * No additional comments specify this
> * Function names don't specifying this
> 
> We should have twin functions like `ProcessOptimisticBlock` and `ProcessValidatedBlock` where the deduplication is addressed underneath the underlying function.
> 
> A good example of this is `ExecuteStateTransition` and `ExecuteStateTransitionNoVerifyAnySig`

Can't work the problem is that at the call site in the blockchain package we need to insert the block in forkchoice before we can actually check if it's optimistic or not. So even if we add helpers like `ProcessOptimisticBlock` and `ProcessValidatedBlock`, we will be using only `ProcessOptimisticBlock` and later `SetOptimisticToValid`.

2022-03-11 16:28 UTC, terencechain approved these changes

2022-03-12 17:23 UTC, terencechain approved these changes

2022-03-12 17:32 UTC, merged