Fix `BaseFeePerGas` endianess
prysmaticlabs/prysm pull request #10376
Opened 2022-03-16 16:15 UTC by terencechain

Fixed payload's `UnmarshalJSON` to use correct endianness on field `BaseFeePerGas`. Added more entropies to some tests

2022-03-16 19:24 UTC, rauljordan approved these changes

2022-03-16 19:26 UTC, rauljordan commented
needs codeowner review

2022-03-16 21:21 UTC, rkapka requested changes

2022-03-16 21:21 UTC, rkapka commented on beacon-chain/state/v3/setters_test.go
> +		BaseFeePerGas:    bytesutil.PadTo([]byte{1, 2, 3, 4}, fieldparams.RootLength),
Please make the same changes in `beacon-chain/native-state/v3/setters_test.go`

2022-03-16 21:28 UTC, rkapka commented on beacon-chain/state/v3/setters_test.go
> +		BaseFeePerGas:    bytesutil.PadTo([]byte{1, 2, 3, 4}, fieldparams.RootLength),
Also here

2022-03-16 21:30 UTC, rkapka approved these changes

2022-03-16 22:12 UTC, merged

2022-03-17 02:08 UTC, nisdas reviewed
A new test case should have been added in rather than modifying existing ones.

2022-03-17 02:25 UTC, terencechain commented
> A new test case should have been added in rather than modifying existing ones.

The old test case is bogus though, and it would have resulted the same regardless of endianess

2022-03-17 02:36 UTC, nisdas commented
> The old test case is bogus though, and it would have resulted the same regardless of endianess

The old test case doesn't seem to have been testing endianess specifically seems just like a basic mock. It would have been good to have one to test the endianess issue specifically.

2022-03-17 02:38 UTC, terencechain commented
> > The old test case is bogus though, and it would have resulted the same regardless of endianess
> 
> The old test case doesn't seem to have been testing endianess specifically seems just like a basic mock. It would have been good to have one to test the endianess issue specifically.

Exactly. That's what was added: https://github.com/prysmaticlabs/prysm/pull/10376/files#diff-19fe51962300879516f288890ebfcb97ae51162dca32b0c5ccc2028a2d7b12fbR81