Process atts and update head before proposing
prysmaticlabs/prysm pull request #10653
Opened 2022-05-06 15:10 UTC by terencechain

This implements https://github.com/ethereum/consensus-specs/pull/2878

Joined work with @potuz 

This PR refactors out `ProcessAttestationsAndUpdateHead` with a lock to only allow one caller at a time to avoid race between:
1. Calling it at slot start
2. Calling it before the proposal

2022-05-06 15:10 UTC, terencechain commented on beacon-chain/blockchain/receive_attestation.go
> +	defer s.processAttestationsLock.Unlock()
This is the only addition from the refactor above

2022-05-06 15:11 UTC, terencechain commented on beacon-chain/rpc/prysm/v1alpha1/validator/proposer_phase0.go
> +		log.WithError(err).Error("Could not process attestations and update head")
Opt it to log an error instead of return error. Error from this call should not prevent block proposal

2022-05-09 21:47 UTC, rauljordan commented on beacon-chain/blockchain/chain_info.go
> +	ProcessAttestationsAndUpdateHead(context.Context) error
Is there no way to separate this? Can head updater have two functions?

2022-05-09 21:48 UTC, rauljordan commented on beacon-chain/blockchain/receive_attestation.go
> +func (s *Service) ProcessAttestationsAndUpdateHead(ctx context.Context) error {
We're combining multiple concerns here. It feels a lot cleaner to have the caller do update head after forkchoice attestations are processed

2022-05-09 22:09 UTC, rauljordan commented on beacon-chain/blockchain/receive_attestation.go
> +// UpdateHead processes fork choice attestations from the pool and updates the head.
We should say that it updates the canonical head of the chain based on information from fork-choice attestations and votes. It requires no external inputs.

2022-05-09 22:15 UTC, rauljordan approved these changes

2022-05-09 23:12 UTC, merged

2022-05-30 10:46 UTC, Dayday10 requested changes
?

2022-05-30 10:50 UTC, Dayday10 commented
Do not merge this account