fuzz: Fix off by one error in sparse merkle trie item insertion
prysmaticlabs/prysm pull request #10668
Opened 2022-05-09 21:42 UTC by prestonvanloon

**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

Off by one error can cause an out of bounds array panic.

**Which issues(s) does this PR fix?**

**Other notes for review**

Found with [fuzzbuzz.io](https://fuzzbuzz.io).

2022-05-10 05:46 UTC, nisdas commented
Can we add a small unit test for this case ?

2022-05-10 05:51 UTC, nisdas requested changes
Also there is the same bug here, which isnt handled in the PR:
https://github.com/prysmaticlabs/prysm/pull/10662/files#diff-1e345f2ed9b4fe9fe77ad2b505742728465d2f4b894ca31704b05ef81f715141R163

2022-05-12 15:52 UTC, prestonvanloon commented
> Can we add a small unit test for this case ?

The checked in fuzz test samples could count as a regression test. 
Do you think that is sufficient? They are run when you do `go test ./...`

2022-05-12 15:52 UTC, prestonvanloon commented
> Also there is the same bug here, which isnt handled in the PR: https://github.com/prysmaticlabs/prysm/pull/10662/files#diff-1e345f2ed9b4fe9fe77ad2b505742728465d2f4b894ca31704b05ef81f715141R163

Yeah, I think all of these sanity checks can be done in the constructor. I'll refactor a bit for this PR

2022-05-13 00:25 UTC, prestonvanloon commented
@nisdas I moved the validator into the constructor

2022-05-13 06:15 UTC, nisdas commented on container/trie/sparse_merkle.go
> +		return errors.New("depth is greater than number of branches")
```suggestion
		return errors.New("depth is greater than or equal to number of branches")
```

2022-05-13 06:16 UTC, nisdas commented on container/trie/sparse_merkle_test.go
> +			errString: "depth is greater than number of branches",
```suggestion
			errString: "depth is greater than or equal to number of branches",
```

2022-05-13 06:17 UTC, nisdas approved these changes

2022-05-13 07:02 UTC, merged