Add builder proposer routine
prysmaticlabs/prysm pull request #10860
Opened 2022-06-10 04:47 UTC by terencechain

This PR adds builder proposer routine to RPC

2022-06-13 21:55 UTC, prestonvanloon requested changes

2022-06-13 21:55 UTC, prestonvanloon commented on beacon-chain/builder/testing/BUILD.bazel
> +    visibility = ["//visibility:public"],
Please add `testonly = True,` and run gazelle

2022-06-13 23:21 UTC, terencechain commented
I'm leaning towards closing this soon, then opening it in incremental fashions after it's successfully tested with mev boost with merge mock and/or real relays. Please don't spend too much time reviewing this. Thanks for the feedbacks @prestonvanloon , I'll add them now

2022-06-21 01:32 UTC, terencechain commented
Breaking this into smaller prs

2022-06-21 01:32 UTC, closed without merging