Fix Fuzz Targets
prysmaticlabs/prysm pull request #11060
Opened 2022-07-15 07:56 UTC by nisdas

**What type of PR is this?**

Fuzzing 

**What does this PR do? Why is it needed?**

This PR applies a few changes to our fuzz targets so that the fuzzer ignores and continues its run in the face
of know errors/limitations(transaction hashing)

**Which issues(s) does this PR fix?**
N.A

**Other notes for review**

2022-07-18 15:31 UTC, rauljordan approved these changes

2022-07-18 15:34 UTC, prestonvanloon commented
I did some debugging and found this in the transactions list.

```
diff: added: ["ahsh"] = "0x26db3ef2c0e5945b24088d6a4165d0bb2959abd848b57891aa041b72518548ab"
      removed: ["hash"] = "0x26db3ef2c0e5945b24088d6a4165d0bb2959abd848b57891aa041b72518548ab"
```

I added this diff print to beacon-chain/powchain/engine_client_fuzz_test.go#L226 @ 6a74dcf35b25ae6a046c0f0e73c40f2fb2417030

```go
		txsA := newGethResp["transactions"].([]interface{})
		txsB := newGethResp2["transactions"].([]interface{})
		diff, same := messagediff.PrettyDiff(txsA[1], txsB[1])
		if !same {
			t.Logf("diff: %s", diff)
		}
```


Test case `beacon-chain/powchain/testdata/fuzz/FuzzExecutionBlock/e6943d1fc1c173256455ba40a35cc81d3e0b8c3d23f346d0181b2674937af25a`
```
go test fuzz v1
[]byte("{\"baseFeePerGas\":\"0x7fffffffffffffff\",\"difficulty\":\"0x7fffffffffffffff\",\"extraData\":\"0x\",\"gasLimit\":\"0xffffffffffffffff\",\"gasUsed\":\"0xffffffffffffffff\",\"hash\":\"0xff01ff01ff01ff01ff01ff01ff01ff0100000000000000000000000000000000\",\"logsBloom\":\"0x6a756e6b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\",\"miner\":\"0x0000000000000000000000000000000000000000\",\"mixHash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"nonce\":\"0x0000000000000000\",\"number\":\"0x7fffffffffffffff\",\"parentHash\":\"0xff01ff01ff01ff01ff01ff01ff01ff0100000000000000000000000000000000\",\"receiptsRoot\":\"0xff01ff01ff01ff01ff01ff01ff01ff0100000000000000000000000000000000\",\"sha3Uncles\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"stateRoot\":\"0xff01ff01ff01ff01ff01ff01ff01ff0100000000000000000000000000000000\",\"timestamp\":\"0x64\",\"totalDifficulty\":\"999999999999999999999999999999999999999\",\"transactions\":[{\"type\":\"0x2\",\"nonce\":\"0xffffffffffffffff\",\"gasPrice\":null,\"maxPriorityFeePerGas\":\"0x7fffffffffffffff\",\"maxFeePerGas\":\"0x7fffffffffffffff\",\"gas\":\"0xffffffffffffffff\",\"value\":\"0x7fffffffffffffff\",\"input\":\"0x72616e646f6d\",\"v\":\"0x0\",\"r\":\"0x7fffffffffffffff\",\"s\":\"0x7fffffffffffffff\",\"to\":\"0x095e7baea6a6c7c4c2dfeb977efac326af552d87\",\"chainId\":\"0x7fffffffffffffff\",\"accessList\":[],\"hash\":\"0x26db3ef2c0e5945b24088d6a4165d0bb2959abd848b57891aa041b72518548ab\"},{\"type\":\"0x2\",\"nonce\":\"0xffffffffffffffff\",\"gasPrice\":null,\"maxPriorityFeePerGas\":\"0x7fffffffffffffff\",\"maxFeePerGas\":\"0x7fffffffffffffff\",\"gas\":\"0xffffffffffffffff\",\"value\":\"0x7fffffffffffffff\",\"input\":\"0x72616e646f6d\",\"v\":\"0x0\",\"r\":\"0x7fffffffffffffff\",\"s\":\"0x7fffffffffffffff\",\"to\":\"0x095e7baea6a6c7c4c2dfeb977efac326af552d87\",\"chainId\":\"0x7fffffffffffffff\",\"accessList\":[],\"ahsh\":\"0x26db3ef2c0e5945b24088d6a4165d0bb2959abd848b57891aa041b72518548ab\"}],\"transactionsRoot\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}")
```
 
Something funky seems to be going on here. I wouldn't write this issue off as an issue with map equality yet.

2022-07-18 15:35 UTC, prestonvanloon requested changes
I am not sure this is a false positive, something strange is happening. See my comment above.

2022-07-26 07:59 UTC, prestonvanloon approved these changes

2022-07-26 08:19 UTC, merged