Add V3 Suffix to All Prysm Packages
prysmaticlabs/prysm pull request #11083
Opened 2022-07-21 16:37 UTC by rauljordan

As part of our V3 release, we need to add v3 suffixes to all Go packages in Prysm to align with go module convention. This makes it so someone doing a go get of Prysm with the v3 suffix will get the right version pulled. 

Fixes #10006

2022-08-15 22:06 UTC, terencechain submitted a review, later dismissed

2022-08-16 08:40 UTC, nisdas commented on beacon-chain/core/epoch/precompute/reward_penalty_test.go
> +	// See: https://github.com/prysmaticlabs/prysm/v3/issues/5593
```suggestion
	// See: https://github.com/prysmaticlabs/prysm/issues/5593
```

2022-08-16 08:40 UTC, nisdas commented on beacon-chain/core/helpers/validators_test.go
> +		{ // Regression test for https://github.com/prysmaticlabs/prysm/v3/issues/4259.
```suggestion
		{ // Regression test for https://github.com/prysmaticlabs/prysm/issues/4259.
```

2022-08-16 08:40 UTC, nisdas commented on beacon-chain/db/alias.go
> +// head info. For head info, use github.com/prysmaticlabs/prysm/v3/blockchain.HeadFetcher.
```suggestion
// head info. For head info, use github.com/prysmaticlabs/prysm/blockchain.HeadFetcher.
```

2022-08-16 08:40 UTC, nisdas commented on beacon-chain/db/alias.go
> +// about head info. For head info, use github.com/prysmaticlabs/prysm/v3/blockchain.HeadFetcher.
```suggestion
// about head info. For head info, use github.com/prysmaticlabs/prysm/blockchain.HeadFetcher.
```

2022-08-16 08:40 UTC, nisdas commented on beacon-chain/db/alias.go
> +// See github.com/prysmaticlabs/prysm/v3/blockchain.HeadFetcher
```suggestion
// See github.com/prysmaticlabs/prysm/blockchain.HeadFetcher
```

2022-08-16 08:40 UTC, nisdas commented on beacon-chain/db/iface/BUILD.bazel
> +    # Other packages must use github.com/prysmaticlabs/prysm/v3/beacon-chain/db.Database alias.
```suggestion
    # Other packages must use github.com/prysmaticlabs/prysm/beacon-chain/db.Database alias.
```

2022-08-16 08:40 UTC, nisdas commented on beacon-chain/db/kv/kv.go
> +// summary, it can be read in https://github.com/prysmaticlabs/prysm/v3/issues/8274.
```suggestion
// summary, it can be read in https://github.com/prysmaticlabs/prysm/issues/8274.
```

2022-08-16 08:40 UTC, nisdas commented on beacon-chain/db/kv/state.go
> +		// look at issue https://github.com/prysmaticlabs/prysm/v3/issues/9262.
```suggestion
		// look at issue https://github.com/prysmaticlabs/prysm/issues/9262.
```

2022-08-16 09:16 UTC, nisdas commented on beacon-chain/rpc/prysm/v1alpha1/validator/attester_test.go
> +	// More background: https://github.com/prysmaticlabs/prysm/v3/issues/2153
```suggestion
	// More background: https://github.com/prysmaticlabs/prysm/issues/2153
```

2022-08-16 09:16 UTC, nisdas commented on beacon-chain/rpc/prysm/v1alpha1/validator/attester_test.go
> +	// See: https://github.com/prysmaticlabs/prysm/v3/issues/5164
```suggestion
	// See: https://github.com/prysmaticlabs/prysm/issues/5164
```

2022-08-16 09:59 UTC, nisdas approved these changes

2022-08-16 11:51 UTC, potuz submitted a review, later dismissed
I did the following
```
find . -name "*.proto" -exec sed -i -e 's/github.com\/prysmaticlabs\/prysm/github.com\/prysmaticlabs\/prysm\/v3/' '{}' \;
```
And similar ones for the bazel and go files. Run go fmt and then looked for lines changes. I got a very different answer than this PR. 

However I looked at the files in this PR with net line changes 
```
$ git diff --numstat origin/develop..HEAD | awk '{if ($1-$2 != 0) print $1-$2,$3}'
37 deps.bzl
```
So only `deps.bzl` has a net line change. I believe only testing this we will really be sure if it was fine.

2022-08-16 11:55 UTC, potuz requested changes
Please review cause this reverts changes to gohashtree and the grpc gateway

2022-08-16 12:01 UTC, potuz approved these changes

2022-08-16 12:20 UTC, merged