Replace `version.BellatrixBlind` with `b.isBlinded`
prysmaticlabs/prysm pull request #11159
Opened 2022-08-03 14:09 UTC by rkapka

**What type of PR is this?**

Refactor

**What does this PR do? Why is it needed?**

Currently our state version and block versions don't align. Blocks use an additional `BellatrixBlind` version, which is not needed for states. Since both types share the same constants, thinking about versions becomes confusing. This PR adds a new `isBlinded` field to several block types, which is used to discern between blinded and regular blocks.

2022-08-03 14:31 UTC, terencechain requested changes
I think we should remove `version.BellatrixBlind`. It'll be easy to spot the disparity. With this PR, half of the code still uses the `version.BellatrixBlind`. I'm a little uncomfortable where half of the code uses `b.isBlinded` and half uses `version.BellatrixBlind`

![Uploading Screen Shot 2022-08-03 at 7.31.46 AM.png…]()

2022-08-08 12:40 UTC, nisdas reviewed
Looks good to me mostly, although being blinded is a property of solely the block body. We might not need to add a `blinded` boolean for the other block types: ex: `SignedBeaconBlock` , `BeaconBlock` . We could just check the block body if it is actually blinded or not.

2022-08-10 13:09 UTC, nisdas approved these changes

2022-08-10 21:07 UTC, terencechain approved these changes

2022-08-10 22:00 UTC, merged