Health check: optimistic status
prysmaticlabs/prysm pull request #11204
Opened 2022-08-11 13:38 UTC by terencechain

Add health checks to cover optimistic cases. In this case, we return errors with message on corrective action

2022-08-11 13:43 UTC, potuz submitted a review, later dismissed

2022-08-11 17:43 UTC, prestonvanloon requested changes

2022-08-11 17:43 UTC, prestonvanloon commented on beacon-chain/blockchain/service.go
> +		return fmt.Errorf("service is optimistic, and only limited service functionality is provided " +
```suggestion
		return errors.New("service is optimistic, and only limited service functionality is provided " +
```

2022-08-11 17:43 UTC, prestonvanloon commented on beacon-chain/rpc/service.go
> +		return fmt.Errorf("service is optimistic, validators can't perform duties " +
```suggestion
		return errors.New("service is optimistic, validators can't perform duties " +
```

2022-08-11 17:43 UTC, prestonvanloon commented on beacon-chain/rpc/service.go
> +		return fmt.Errorf("failed to check if service is optimistic: %v", err)
```suggestion
		return errors.Wrap(err, "failed to check if service is optimistic")
```

2022-08-11 17:43 UTC, prestonvanloon commented on beacon-chain/blockchain/service.go
> +		return fmt.Errorf("failed to check if service is optimistic: %v", err)
```suggestion
		return errors.Wrap(err, "failed to check if service is optimistic")
```

2022-08-11 19:15 UTC, rauljordan commented
@prestonvanloon PTAL again

2022-08-15 14:31 UTC, prestonvanloon approved these changes

2022-08-15 14:45 UTC, merged