Register validator beacon api
prysmaticlabs/prysm pull request #11225
Opened 2022-08-15 19:15 UTC by james-prysm

**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**
This PR adds the HTTP REST Beacon API endpoint ( [spec list here ](https://ethereum.github.io/beacon-APIs/#/Validator/registerValidator)) for the validator registration API endpoint.

**Which issues(s) does this PR fix?**

Fixes #11220

2022-08-15 20:08 UTC, terencechain commented on beacon-chain/rpc/eth/validator/validator.go
> +		return &empty.Empty{}, status.Errorf(codes.InvalidArgument, "Could not register block builder: %v", builder.ErrNoBuilder)
```suggestion
		return &empty.Empty{}, status.Errorf(codes.Internal, "Could not register block builder: %v", builder.ErrNoBuilder)
```

2022-08-16 12:22 UTC, rkapka requested changes
This also needs API Middleware setup

2022-08-16 12:22 UTC, rkapka commented on beacon-chain/rpc/eth/validator/validator.go
> +
```suggestion
```

2022-08-16 12:22 UTC, rkapka commented on beacon-chain/rpc/eth/validator/validator.go
> +	ctx, span := trace.StartSpan(ctx, "validator.ValidatorRegistration")
```suggestion
	ctx, span := trace.StartSpan(ctx, "validator.SubmitValidatorRegistration")
```

2022-08-16 12:22 UTC, rkapka commented on beacon-chain/rpc/eth/validator/validator.go
> +		return &empty.Empty{}, status.Errorf(codes.InvalidArgument, "validator registration request is empty")
```suggestion
		return &empty.Empty{}, status.Errorf(codes.InvalidArgument, "Validator registration request is empty")
```

2022-08-17 11:17 UTC, rkapka approved these changes

2022-08-17 11:41 UTC, merged