Beacon api: propoerly submit blind block
prysmaticlabs/prysm pull request #11483
Opened 2022-09-21 21:40 UTC by terencechain

**What type of PR is this?**

> Bug fix

**What does this PR do? Why is it needed?**

When using beacon API to submit a blind block, it must first go through mev boost/relayer/builder to retrieve the full block. This PR made sure of that. The status duo is to broadcast the blind block, and that's not going to work

**Which issues(s) does this PR fix?**

Fixes #11477

**Other notes for review**

N/A

2022-09-21 22:32 UTC, rkapka requested changes
We also have to fix `SubmitBlindedBlockSSZ`

2022-09-21 23:00 UTC, terencechain commented
> We also have to fix `SubmitBlindedBlockSSZ`

Fixed. thanks!

2022-09-22 19:50 UTC, rkapka commented on beacon-chain/rpc/eth/beacon/blocks.go
> +			return &emptypb.Empty{}, status.Errorf(codes.Internal, "Could not get blind block: %v", err)
```suggestion
			return &emptypb.Empty{}, status.Errorf(codes.Internal, "Could not get blinded block: %v", err)
```

2022-09-22 19:50 UTC, rkapka commented on beacon-chain/rpc/eth/beacon/blocks.go
> +		return status.Errorf(codes.Internal, "Could not propose blind block: %v", err)
```suggestion
		return status.Errorf(codes.Internal, "Could not propose blinded block: %v", err)
```

2022-09-22 19:56 UTC, rkapka approved these changes

2022-09-22 20:13 UTC, merged