Withdrawal epoch transition
prysmaticlabs/prysm pull request #11590
Opened 2022-10-27 16:27 UTC by potuz

Implement the main loop `process_withdrawals_into_queue` from https://github.com/ethereum/consensus-specs/pull/3042

**Note to reviewers:** 
- Review only if  the spec PR is approved/merged
- Review only after #11570 has merged 
- There are proto changes and breaking changes to the protobuf messages but on Capella structures that have not been used.

2022-10-27 17:05 UTC, terencechain requested changes

2022-10-27 17:11 UTC, potuz commented on proto/prysm/v1alpha1/attestation/attestation_utils.go
> +//	 return bls.FastAggregateVerify(pubkeys, signing_root, indexed_attestation.signature)
I did not touch this file

2022-10-27 17:11 UTC, potuz commented on proto/prysm/v1alpha1/attestation/attestation_utils.go
> +//	 return bls.FastAggregateVerify(pubkeys, signing_root, indexed_attestation.signature)
Ohh it's the last commit is bogus, just a sec

2022-10-31 17:54 UTC, saolyn commented on beacon-chain/core/capella/transition.go
> +			s, err = withdrawBalance(s, index, balance-params.BeaconConfig().MaxEffectiveBalance)
It looks like you accidentally changed `params` to `balance-params` here

2022-11-04 12:18 UTC, potuz commented
Closing since epoch transition will not change in the new design

2022-11-04 12:18 UTC, closed without merging