Add REST implementation for `MultipleValidatorStatus`
prysmaticlabs/prysm pull request #11786
Opened 2022-12-16 14:21 UTC by nalepae

### What type of PR is this?
Feature

### Related gitHub issue:
https://github.com/prysmaticlabs/prysm/issues/11580

### What does this PR do? Why is it needed?
This adds an implementation for the `MultipleValidatorStatus` validator client method by calling the Beacon Node REST API instead of the gRPC one.

### Notes for reviewers:
I tried to mimic https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/rpc/prysm/v1alpha1/validator/status.go#L55-L98.

A list of validators keys and validator indexes are given in inputs.
- If the input validator key corresponds to an existing validator, then nothing fancy is done.
- If the input validator key does not correspond to an existing validator, then the corresponding validator status is set as `unknown` and the corresponding validator index is set at the highest possible `uint64` value.
- If the input validator index does not correspond to an existing validator, then the corresponding validator is dropped.

Compared to gRPC version, I did not keep the same order in the outputs.
I checked in the codebase where `MultipleValidatorStatus` is used, and did not noticed any need for a specific output order.

2022-12-19 17:05 UTC, rkapka requested changes

2022-12-19 17:05 UTC, rkapka commented on validator/client/beacon-api/status.go
> +	validatorsStatus := make([]*ethpb.ValidatorStatusResponse, totalLen)
Let's move these variables right before the `for` loop because that's where you start using these them.

2022-12-19 17:30 UTC, rkapka commented on validator/client/beacon-api/status.go
> +		// Set PositionInActivationQueue
Let's extract this to a private function `setPositionInActivationQueue`

2022-12-20 18:24 UTC, nalepae commented on validator/client/beacon-api/status.go
> +				isLastActivatedValidatorIndexRetrieved = true
With the current implementation, we ensure the 
```c.stateValidatorsProvider.GetStateValidators(nil, nil, []string{"active"})``` call
is done (at most once) if at least one validator is in `PENDING`, `PARTIALLY_DEPOSITED` or `DEPOSITED` state.

Unless I'm mistaken, we don't need to compute `validatorStatus.PositionInActivationQueue` (and so we don't need to retrieve `lastActivatedValidatorIndex`) for validators which are not in `PENDING`, `PARTIALLY_DEPOSITED` or `DEPOSITED` state.

If we retrieve `lastActivatedValidatorIndex` before the `for` loop, we may do an extra call to the beacon node (call which retrieve the whole list of validators) for nothing, in the case no input validators is in this set of states.

I'm OK to move the call outside of the loop, I just want to be sure it's OK to do the (maybe useless) extra call to the beacon node.

2022-12-20 18:43 UTC, nalepae commented on validator/client/beacon-api/status.go
> +				isLastActivatedValidatorIndexRetrieved = true
> (doing it inside the loop redundantly makes the same call in each iteration).

It's the whole purpose of `isLastActivatedValidatorIndexRetrieved` variable (not to make the same call in each iteration). We do the call at most once.

2022-12-20 19:12 UTC, nalepae commented on validator/client/beacon-api/status.go
> +				isLastActivatedValidatorIndexRetrieved = true
**Current implementation:**
The `c.stateValidatorsProvider.GetStateValidators(nil, nil, []string{"active"}` BN call is done at most once.
- It is done exactly once if at least one validator is in `PENDING`, `PARTIALLY_DEPOSITED` or `DEPOSITED` state.
- It is NOT done at all if none of the validators is in `PENDING`, `PARTIALLY_DEPOSITED` or `DEPOSITED` state.

**If we retrieve `lastActivatedValidatorIndex` before the for loop:**
The `c.stateValidatorsProvider.GetStateValidators(nil, nil, []string{"active"}` BN call will always be done exactly once, even if not needed (aka none of the validators is in `PENDING`, `PARTIALLY_DEPOSITED` or `DEPOSITED` state.)

> (doing it inside the loop redundantly makes the same call in each iteration).

It's the whole purpose of `isLastActivatedValidatorIndexRetrieved` variable (not to make the same call in each iteration). We do the call at most once.

2022-12-22 11:28 UTC, rkapka commented on validator/client/beacon-api/status.go
> +				isLastActivatedValidatorIndexRetrieved = true
> It's the whole purpose of isLastActivatedValidatorIndexRetrieved variable (not to make the same call in each iteration). We do the call at most once.

I see it now, it's declared before the `for` loop.

2022-12-27 01:22 UTC, rkapka approved these changes

2023-01-03 18:48 UTC, nalepae commented
I cannot reproduce the failed `sync_completed` e2e test locally:

```
    --- PASS: TestEndToEnd_MinimalConfig/sync_completed (0.50s)
```

2023-01-03 20:41 UTC, nalepae commented
It seems some tests e2e tests fail because of `No space left on device` error: https://buildkite.com/prysmatic-labs/prysm/builds/69708#018577a1-b5ea-40ba-8922-2a0854c91921
(exemple: line 218)

2023-01-04 23:15 UTC, merged