beacon-chain, config: get consensus values from beacon config
prysmaticlabs/prysm pull request #11798
Opened 2022-12-19 18:02 UTC by gballet

**What type of PR is this?**

Other

**What does this PR do? Why is it needed?**

This allows prysm to get some of its consensus parameters from the config file, instead of getting them from a hardcoded file. This is necessary to support e.g. the gnosis chain, that has a different slot time.

Another approach I considered was to store the hardcoded values for the gnosis chain inside a file in `config/fieldparams`, protected by a tag. I think this PR is the better approach, however, as adding other chains would require adding a file each time, when the config file can be tweaked instead.

2022-12-20 01:17 UTC, terencechain approved these changes
Ty!

2022-12-20 08:22 UTC, nisdas requested changes
I will need to think on this more, but the main reason it is a hardcoded value rather than something that can be configured at runtime is because presets are meant to be initialized at compile time. For context, you can take a look at this PR:
https://github.com/prysmaticlabs/prysm/pull/10007

I understand, that this won't work with gnosis chain currently which requires it being changed at runtime.

2022-12-20 16:25 UTC, gballet commented
That makes sense, I'll work on the gnosis preset then.

2022-12-20 23:55 UTC, nisdas reviewed
@gballet So we talked internally and while the change isn't great, we would be okay with this. Given that we are the only client that has this strict requirement, it seems that it has limited benefit to forcing this to be a compile time constant

2022-12-20 23:55 UTC, nisdas commented on config/params/config.go
> +func (b *BeaconChainConfig) Eth1DataVotesLength() uint64 {
Lets add a comment for each new method

2022-12-22 15:10 UTC, gballet commented
@nisdas thanks for your feedback, I have added the required comments. Let me know if you would like other changes.

2023-01-24 16:58 UTC, nisdas approved these changes

2023-01-25 10:42 UTC, merged