Add REST implementation for Validator's `SubscribeCommitteeSubnets`
prysmaticlabs/prysm pull request #11804
Opened 2022-12-21 09:36 UTC by PatriceVignola

**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**

It adds the `SubscribeCommitteeSubnets` REST API endpoint for the validator.

**Other notes for review**

I started working on this feature before https://github.com/prysmaticlabs/prysm/pull/11723 and all the tests were passing. But after merging with this change, the E2E tests started logging errors in the beacon node (although the tests are still passing somehow). I believe this is because `StateBySlot` is returning an error if the slot is in the future, but epochs at `epoch + 1` should be allowed as per the API spec. The unit tests are still passing because `StateBySlot` is mocked inside the validator duties tests, which means that this code doesn't get executed for `epoch + 1`. I'm not familiar enough with that part of the code to make a change and be sure that it doesn't break something else, especially since the change was a bug fix for another issue in the first place. It would be ideal if this issue gets fixed by another PR before my PR gets merged.

Also, I had to slightly modify the signature of the interface in this PR since validator indices are needed to get the duties, and retrieving the duties is necessary to get the `committees_at_slot` values.

2023-01-06 23:15 UTC, james-prysm commented on validator/client/validator.go
> +			subscribeValidatorIndices = append(subscribeValidatorIndices, validatorIndex)
cool so this is now collecting indicies for both current and next epochs, I saw a check on our old gRPC that tries to collect a list of indicies based on head and their respective epoch with this I think we just collect both here.

2023-01-06 23:16 UTC, james-prysm commented on validator/client/beacon-api/subscribe_committee_subnets.go
> +	for index := range in.CommitteeIds {
was wondering why it was looping through the committeeIds first but saw the check `len(in.CommitteeIds) != len(in.Slots)`

2023-01-10 02:16 UTC, james-prysm commented
I believe there was an additional fix for attester duties in #11806

2023-01-16 13:06 UTC, rkapka requested changes

2023-01-16 13:06 UTC, rkapka commented on validator/client/beacon-api/subscribe_committee_subnets_test.go
> +const subscrimeCommitteeSubnetsTestEndpoint = "/eth/v1/validator/beacon_committee_subscriptions"
`subscrime` -> `subscribe`

2023-01-16 19:35 UTC, PatriceVignola commented on validator/client/beacon-api/subscribe_committee_subnets.go
> +			duties, err := c.dutiesProvider.GetAttesterDuties(ctx, epoch, validatorIndices)
Below on line 53, we loop through all slots obtained for the epoch and add them to the map, so essentially we never query an epoch more than once. Even though duties are queried from a specific epoch, committees are slot-based so it simplifies the logic to have a `slot -> committee` map.

2023-01-17 15:40 UTC, rkapka approved these changes

2023-01-18 21:21 UTC, james-prysm approved these changes

2023-01-18 21:21 UTC, merged