implement REST endpoint to force broadcast of pending bls changes
prysmaticlabs/prysm pull request #11871
Opened 2023-01-13 14:52 UTC by potuz

This PR implements a REST endpoint to force the beacon to broadcast all pending BLS changes in the operation pool

2023-01-13 17:28 UTC, rkapka commented on beacon-chain/rpc/apimiddleware/structs.go
> +}
Maybe let's create an empty struct that can be reused whenever we want to POST without data.
```
type EmptyRequest struct {}
```

2023-01-13 18:38 UTC, terencechain requested changes
Codewise, this looks good. My only ask:
Can anyone write up a short rationale and user guide on recommendations "how to use this" before we merge this?

2023-01-19 22:05 UTC, james-prysm commented
Theres some suggestions from deepsource on this.

2023-01-20 16:05 UTC, james-prysm commented on beacon-chain/rpc/eth/beacon/pool.go
> +// operations pool.
you responded on slack but could you add some use-case comments here as the reason for having this endpoint is less obvious.

2023-02-17 21:49 UTC, potuz commented
Close as not needed

2023-02-17 21:49 UTC, closed without merging