Enhance block arrival delay metrics
prysmaticlabs/prysm pull request #11897
Opened 2023-01-20 04:56 UTC by terencechain

This PR is inspired by https://github.com/sigp/lighthouse/pull/3894 (Credit to @AgeManning). There has been large-block experiments on testnet. As it turns out, prysm nodes have not captured delay metrics in their best form. I think we can do a better job with greater resolution around histograms and with a gauge that tracks the last block delay. Understand that also depends on polling resolution so we can lose granular information but it's better than nothing

2023-01-20 11:48 UTC, potuz requested changes

2023-01-20 11:48 UTC, potuz commented on beacon-chain/sync/metrics.go
> +			Buckets: []float64{100, 200, 300, 400, 500, 750, 1000, 1250, 1500, 1750, 2000, 2500, 3000, 3500, 4000, 5000, 6000, 7000, 8000, 9000, 10000, 15000, 20000},
I'm not comfortable with these aditions. Was the problem that we didn't have granularity or the problem was that we didn't have the right buckets. I would feel much better if we use a logarithmic scale here, but with the same number of ticks.

2023-01-23 08:44 UTC, nisdas approved these changes

2023-02-02 14:35 UTC, potuz approved these changes

2023-02-02 15:43 UTC, merged