Add REST API endpoint for node client's `GetGenesis`
prysmaticlabs/prysm pull request #12168
Opened 2023-03-21 05:55 UTC by PatriceVignola

**What type of PR is this?**

Feature

**What does this PR do? Why is it needed?**

It adds the REST API endpoint for node client's `GetGenesis`.

2023-03-23 04:04 UTC, PatriceVignola commented
@rkapka FYI

2023-03-24 11:54 UTC, rkapka requested changes

2023-03-24 11:54 UTC, rkapka commented on validator/client/beacon-api/beacon_api_node_client_test.go
> +			name: "fails to decode deposit contract address",
the name if this test is incorrect

2023-03-28 11:17 UTC, rkapka approved these changes

2023-03-28 11:36 UTC, merged