Add support for non-blinded blocks to `ProduceBlindedBlock`
prysmaticlabs/prysm pull request #12309
Opened 2023-04-19 12:05 UTC by rkapka

**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

`ProduceBlindedBlock` currently assumes that v1alpha1 server will return blinded blocks. This doesn't have to be true.

**Which issues(s) does this PR fix?**

Fixes #12103

**Other notes for review**

No tests because test setup is really difficult. I have an idea on how to simplify tests for this function, allowing to test the new code easily too, but it will be a bigger PR so I want to keep it separate.

2023-04-19 12:11 UTC, saolyn reviewed
Can you add some tests to cover these new additions.

2023-04-19 12:48 UTC, terencechain requested changes
I don't think this is correct, the beacon api stated the return should be blinded block or error. In this case, wouldn't error be most appropriate 

Really the best option is to fix the underly inefficiency so it actually can return blind block instead of error

2023-04-20 16:28 UTC, james-prysm submitted a review, later dismissed
I'm ok with adding additional defensive checks.

2023-04-20 16:39 UTC, james-prysm approved these changes

2023-04-21 04:10 UTC, terencechain approved these changes

2023-04-21 09:41 UTC, merged