InsertFinalizedDeposits: return an error
prysmaticlabs/prysm pull request #12342
Opened 2023-04-27 10:16 UTC by saolyn

**What type of PR is this?**

Error handling

**What does this PR do? Why is it needed?**

Adds the error return type to `InsertFinalizedDeposits` and modifies it's usages to handle the error. 
We modified the code in the new deposit tree to return the errors.

**Other notes for review**

2023-04-27 12:13 UTC, rkapka requested changes

2023-04-27 12:13 UTC, rkapka commented on beacon-chain/blockchain/process_block_test.go
> +	require.NoError(t, err)
You can write this and the other ones in one line:
```
require.NoError(t, depositCache.InsertFinalizedDeposits(ctx, 2))
```

2023-04-27 12:13 UTC, rkapka commented on beacon-chain/cache/depositcache/deposits_cache.go
> +			//log.WithError(err).Error("Could not hash deposit data. Finalized deposit cache not updated.")
please remove comment

2023-04-27 12:13 UTC, rkapka commented on beacon-chain/cache/depositcache/deposits_cache.go
> +			return errors.Wrap(err, "Could not hash deposit data. Finalized deposit cache not updated.")
Errors should be lowercase and without punctuation. A better message would be `could not hash deposit data`

2023-04-27 12:13 UTC, rkapka commented on beacon-chain/cache/depositcache/deposits_cache.go
> +			return errors.Wrap(err, "Could not insert deposit hash")
errors should be lowercase and without punctuation

2023-04-27 17:13 UTC, rauljordan commented
hi @rkapka this should be ready again

2023-04-28 20:59 UTC, rkapka approved these changes

2023-04-28 20:59 UTC, merged