Check blob exists in pending queue before requesting from peer
prysmaticlabs/prysm pull request #13013
Opened 2023-10-06 18:14 UTC by terencechain

Fixes an issue where redundant requests were made to peers for blocks already present in the pending queue, adversely affecting peer scoring.

#### Changes:

1. **Pending Attestation Queue**: Check if the block exists in the queue before appending pending roots.
2. **Batch Root Request**: Similar to `BlockBeingSynced`, removes the root from the request list if it's already seen.

This PR adds checks in both places for future-proofing.

2023-10-06 19:01 UTC, potuz submitted a review, later dismissed

2023-10-06 19:18 UTC, potuz requested changes

2023-10-06 19:18 UTC, potuz commented on beacon-chain/sync/pending_attestations_queue.go
> +			seen := s.seenPendingBlocks[bRoot]
if you are going to add a lock you need to lock in a lot of places where `seenPendingBlocks` is accessed

2023-10-07 02:41 UTC, nisdas approved these changes

2023-10-09 14:21 UTC, potuz approved these changes

2023-10-09 17:35 UTC, merged