Remove sidecars with invalid proofs
prysmaticlabs/prysm pull request #13070
Opened 2023-10-18 20:05 UTC by potuz

Remove sidecars when they have invalid proofs. Also rename function in anticipation of an existing DeleteBlobSidecar

2023-10-18 20:07 UTC, potuz commented on beacon-chain/blockchain/process_block.go
> +				log.WithField("root", fmt.Sprintf("%#x", root)).Warn("removing blob sidecars with invalid proofs")
There are two possible errors, the length of commitments is not right or there is an invalid proof. It's safe to remove blobs anyway here.

2023-10-18 20:24 UTC, kasey submitted a review, later dismissed

2023-10-18 22:38 UTC, terencechain requested changes
Instead if merging this. Why not have Devnet nodes run from this branch for now? And we can merge in the real fixes in a few days?

2023-10-18 23:12 UTC, terencechain approved these changes
Discussed offline. Ok to merge now while we work on the cache. Thanks Potuz!

2023-10-19 03:56 UTC, terencechain reviewed
Reviewing this more, you'll want to remove the sidecars in the for loop to save 4 seconds

2023-10-19 04:02 UTC, nisdas commented on beacon-chain/blockchain/process_block.go
> +				if err2 := s.cfg.BeaconDB.DeleteBlobSidecars(ctx, root); err2 != nil {
maybe rename this to `deletionErr` ? we don't want to overwrite the original error as it still has to be returned to the caller

2023-10-19 04:03 UTC, terencechain commented on beacon-chain/blockchain/process_block.go
> +				if err2 := s.cfg.BeaconDB.DeleteBlobSidecars(ctx, root); err2 != nil {
Sorry I missed that

2023-10-19 14:30 UTC, terencechain approved these changes

2023-10-19 15:33 UTC, merged