use different keys for the proposer indices cache
prysmaticlabs/prysm pull request #13272
Opened 2023-12-05 19:52 UTC by potuz

This PR removes an LRU cache and moves to a cache that keeps maps indexed as

epoch -> state root -> proposer indices. 

They are updated in the same places as before and they are pruned on each update.

2023-12-06 10:41 UTC, potuz commented
> Fails to build

Yeah not ready yet, want to add a good API to use by Kasey

2023-12-06 14:42 UTC, terencechain requested changes

2023-12-06 14:42 UTC, terencechain commented on beacon-chain/blockchain/process_block.go
> +	r := [32]byte(st.LatestBlockHeader().BodyRoot)
This looks wrong. Why are we using the `BodyRoot` all of a sudden? Shouldn't it be `HashTreeRoot`?

2023-12-19 12:37 UTC, potuz commented on beacon-chain/blockchain/process_block.go
> +	s.cfg.ForkChoiceStore.RLock()
yes, there are two calls, one is locked, the other isn't

2023-12-19 12:47 UTC, potuz commented on beacon-chain/blockchain/process_block.go
> +	}
The reason I have it in the end of that block is to be able to return easily

2023-12-19 13:14 UTC, terencechain approved these changes

2023-12-19 13:38 UTC, merged