fixing the handling for certain cases
prysmaticlabs/prysm pull request #13585
Opened 2024-02-05 21:15 UTC by james-prysm

**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

fixes the [/eth/v1/beacon/blob_sidecars/{block_id}](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getBlobSidecars) endpoint to handl the additional cases below correctly without a 500 error. currently, we will try to use the root even if the block doesn't exist which doesn't correctly handle all our cases.

- block exists, no commitment, 200 w/ empty list

- block exists, has commitments, inside retention period (greater of protocol- or user-specified) serve then w/ 200 unless we hit an error reading them. we are technically not supposed to import a block to forkchoice unless we have the blobs, so the nuance here is if we can't find the file and we are inside the protocol-defined retention period, then it's actually a 500.

**Which issues(s) does this PR fix?**

related to https://github.com/prysmaticlabs/prysm/issues/13134

2024-02-05 21:37 UTC, james-prysm commented on beacon-chain/rpc/lookup/blocker.go
> +	if !p.BeaconDB.HasBlock(ctx, bytesutil.ToBytes32(root)) {
maybe this isn't needed if i just use `p.BeaconDB.Block()`

2024-02-06 17:04 UTC, rkapka requested changes

2024-02-06 17:04 UTC, rkapka commented on beacon-chain/rpc/eth/blob/handlers_test.go
> +		u := "http://foo.example/123"
How come is the block outside of retention period when the retention period is set to 4096*32 slots?

2024-02-06 21:14 UTC, rkapka approved these changes

2024-02-06 22:37 UTC, merged