[PeerDAS] rework ENR custody_subnet_count related code
prysmaticlabs/prysm pull request #14077
Opened 2024-06-03 22:03 UTC by 0x00101010

**What type of PR is this?**
Feature

**What does this PR do? Why is it needed?**
Rework ENR custody_subnet_count related code

**Which issues(s) does this PR fix?**

Fixes #

**Other notes for review**

2024-06-04 09:31 UTC, nalepae commented on beacon-chain/p2p/discovery.go
> +	quickProtocolEnrKey      = "quic"
This const is never used.
I guess you wanted to do something like:
```go
func (quicProtocol) ENRKey() string { return quickProtocolEnrKey }
```
?

2024-06-04 09:31 UTC, nalepae commented on beacon-chain/p2p/discovery.go
> +	custodySubnetCountEnrKey = "custody_subnet_count"
I think you miss something like:

```go
func (CustodySubnetCount) ENRKey() string { return custodySubnetCountEnrKey }
```

2024-06-04 09:43 UTC, nalepae commented
Thank you for your pull request!

The majority of your changes are scheduled for deletion because of https://github.com/ethereum/consensus-specs/pull/3772.

If you wish, you can implement this specification change into Prysm, so we'll be able to merge it once the specification PR is merged. (In the contrary, just fix the few comments I made and we'll merge this one.)

2024-06-04 16:07 UTC, 0x00101010 commented
> Thank you for your pull request!
> 
> The majority of your changes are scheduled for deletion because of [ethereum/consensus-specs#3772](https://github.com/ethereum/consensus-specs/pull/3772).
> 
> If you wish, you can implement this specification change into Prysm, so we'll be able to merge it once the specification PR is merged. (In the contrary, just fix the few comments I made and we'll merge this one.)

@nalepae updated, let me know if it looks good

2024-06-05 08:56 UTC, nalepae commented
Thank you!

I approved it, and set it as `blocked` until https://github.com/ethereum/consensus-specs/pull/3772 is merged.

2024-06-05 08:56 UTC, nalepae approved these changes

2024-06-05 08:57 UTC, nalepae requested changes
You need to run
```
bazel run //:gazelle -- fix
```

(CI fails.)

2024-06-05 23:07 UTC, nalepae approved these changes

2024-06-05 23:08 UTC, nalepae commented
Approved, thanks!

2024-06-12 20:35 UTC, merged