refactor: enable errorlint and refactor code
prysmaticlabs/prysm pull request #14110
Opened 2024-06-14 09:36 UTC by hoanguyenkh

**What type of PR is this?**

> Uncomment one line below and remove others.
>
> Bug fix
> Feature
> Documentation
> Other

**What does this PR do? Why is it needed?**

**Which issues(s) does this PR fix?**

Fixes #

**Other notes for review**

2024-06-15 01:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prysmaticlabs/prysm?pullRequest=14110) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prysmaticlabs/prysm?pullRequest=14110) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prysmaticlabs/prysm?pullRequest=14110) it.</sub>

2024-06-16 16:03 UTC, terencechain submitted a review, later dismissed

2024-06-24 02:11 UTC, hoanguyenkh commented
hi @nalepae @saolyn can you merge PR?

2024-06-24 14:32 UTC, prestonvanloon requested changes
Apologies for the eager approval. Upon closer review, there are some things that need to be addressed. Thanks

2024-06-24 14:32 UTC, prestonvanloon commented on beacon-chain/node/registration/p2p.go
>  		}
This is a logic change. Please revert

2024-06-24 14:32 UTC, prestonvanloon commented on beacon-chain/rpc/eth/beacon/handlers_validator.go
> +
```suggestion
```
You may need to run gofmt or goimports too

2024-06-24 14:32 UTC, prestonvanloon commented on beacon-chain/rpc/eth/shared/errors.go
> +
```suggestion
```

You may need to run gofmt or goimports too

2024-06-24 14:32 UTC, prestonvanloon commented on beacon-chain/sync/rpc.go
> +
```suggestion
```
You may need to run gofmt or goimports too

2024-06-24 14:32 UTC, prestonvanloon commented on beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
> +	"github.com/pkg/errors"
Please put this import with the other non-standard imports. The second section starting on line 12

2024-06-24 14:32 UTC, prestonvanloon commented on cmd/prysmctl/p2p/handler.go
> +
```suggestion
```

You may need to run gofmt or goimports too

2024-06-24 14:32 UTC, prestonvanloon commented on config/params/loader.go
>  		}
This is a logic change. Please revert

2024-06-24 14:32 UTC, prestonvanloon commented on tools/replay-http/main.go
> +
```suggestion
```

You may need to run gofmt or goimports too

2024-06-24 14:32 UTC, prestonvanloon commented on validator/graffiti/parse_graffiti.go
>  	}
This is a logic change, please revert

2024-06-24 14:40 UTC, prestonvanloon commented
You need to run gazelle on this PR.

```
bazel run //:gazelle
```

2024-06-24 15:47 UTC, hoanguyenkh commented
thank @prestonvanloon for feedback, please check it again! thank you

2024-06-26 17:03 UTC, prestonvanloon approved these changes
LGTM, thank you!!

2024-07-01 14:04 UTC, hoanguyenkh commented
can you help me merge it @prestonvanloon

2024-07-04 22:51 UTC, merged