Process withdrawal
prysmaticlabs/prysm pull request #14297
Opened 2024-08-02 18:21 UTC by Redidacove

What type of PR is this?
This is a helper function implementation pr for processing withdrawals

What does this PR do? Why is it needed?
This Pr implements the process_withdrawals fn acc to the eip7732 specs implementation

2024-08-05 12:31 UTC, potuz commented on beacon-chain/core/blocks/withdrawals.go
> -	expectedWithdrawals, partialWithdrawalsCount, err := st.ExpectedWithdrawals()
The godoc needs to be updated to ePBS.

2024-08-05 12:31 UTC, potuz commented on beacon-chain/core/blocks/withdrawals.go
> +			wdRoot = bytesutil.ToBytes32(r)
```suggestion
			copy(wdRoot[:], r)
```

2024-08-05 12:31 UTC, potuz commented on beacon-chain/core/blocks/withdrawals_test.go
> +				ExpectedError: true,
Why an error here if the parent node is not full we don't return an error.

2024-08-09 11:24 UTC, potuz commented on beacon-chain/core/blocks/withdrawals.go
> +//
This does not match the python declaration

2024-08-12 20:31 UTC, potuz commented on beacon-chain/core/blocks/withdrawals.go
> +
```suggestion
```

2024-08-12 20:31 UTC, potuz commented on beacon-chain/core/blocks/withdrawals_test.go
> +
```suggestion
```

2024-08-13 07:13 UTC, terencechain requested changes
I dont think [df7b205](https://github.com/prysmaticlabs/prysm/pull/14297/commits/df7b2057279e5cdd77c0a52276a901b8734df42d) is correct, instead of duplicating the entire test for test setup, you could have just initialized the field directly. Adding this fixes the panic for me:

<img width="976" alt="Screenshot 2024-08-13 at 7 11 32 AM" src="https://github.com/user-attachments/assets/887735ea-6d39-4307-a24c-4c81e2453689">

2024-08-13 12:41 UTC, merged