Remove identical beacon state
prysmaticlabs/prysm pull request #14338
Opened 2024-08-13 12:20 UTC by saolyn

**What type of PR is this?**

Cleanup

**What does this PR do? Why is it needed?**

We had two completely identical beacon states with the only difference being the flag at the top eg. `//go:build minimal` this PR removes one and renames the file to be a general `beacon_state` used by both `minimal` and `mainnet`.

**Which issues(s) does this PR fix?**

N/A

**Other notes for review**

2024-08-13 19:53 UTC, prestonvanloon approved these changes
LGTM. These two files were identical. 

@rkapka do you see any issue with this?

2024-08-14 08:21 UTC, nisdas requested changes
This is incorrect, we need 2 versions of the state.  A mainnet state is not compatible with a minimal state

2024-08-14 09:22 UTC, nisdas approved these changes
After talking with @rkapka , it is fine to remove it and just use 1 state instance

2024-08-14 09:23 UTC, rkapka approved these changes

2024-08-14 10:24 UTC, merged