Fix 'data_column_sidecar_computation' metric align with PeerDAS metrics specs
prysmaticlabs/prysm pull request #14574
Opened 2024-10-23 18:31 UTC by KatyaRyazantseva

**What type of PR is this?**

 Feature

**What does this PR do? Why is it needed?**
This PR adjusts PeerDAS metric `beacon_data_column_sidecar_computation_seconds` align with the [PeerDAS metrics specs](https://github.com/ethereum/beacon-metrics/pull/14):
- rename the metric
- change milliseconds to seconds

**Which issues(s) does this PR fix?**

Fixes (partially) #14129

**Other notes for review**

**Acknowledgements**

- [x] I have read [CONTRIBUTING.md](https://github.com/prysmaticlabs/prysm/blob/develop/CONTRIBUTING.md).
- [ ] I have made an appropriate entry to [CHANGELOG.md](https://github.com/prysmaticlabs/prysm/blob/develop/CHANGELOG.md).
- [x] I have added a description to this PR with sufficient context for reviewers to understand this PR.

2024-10-23 18:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prysmaticlabs/prysm?pullRequest=14574) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/prysmaticlabs/prysm?pullRequest=14574) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: nisdas<br/>:white_check_mark: jtraglia<br/>:white_check_mark: nalepae<br/>:white_check_mark: kevaundray<br/>:white_check_mark: 0x00101010<br/>:x: KatyaRyazantseva<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prysmaticlabs/prysm?pullRequest=14574) it.</sub>

2024-10-24 04:16 UTC, nisdas requested changes
I disagree with changing the unit to seconds. Most metrics recorded are going to be simply 0,1 or 2 which isn't useful at all. Milliseconds is a much more useful unit of time to gauge (1400ms vs 1s) as you have much greater granularity

2024-11-01 14:26 UTC, nalepae commented
@KatyaRyazantseva sorry for the inconvenience, would it be possible to reset your PR on top of the current `peerDAS` branch?

(I rebased the `peerDAS` branch on top on `develop` after you created your PR, so that's why there is plenty of commits.)

2024-11-01 14:29 UTC, nalepae commented
> I disagree with changing the unit to seconds. Most metrics recorded are going to be simply 0,1 or 2 which isn't useful at all. Milliseconds is a much more useful unit of time to gauge (1400ms vs 1s) as you have much greater granularity

The metric is a float, not an int right?

If so; instead of 1400ms, we should have 1.4s, not 1s.

2024-11-02 04:37 UTC, nisdas commented
> The metric is a float, not an int right?

> If so; instead of 1400ms, we should have 1.4s, not 1s.

Metric is a float but the time is not, It is a discrete quantity, so if you ask it for seconds you will only get 1 instead of 1.4

2025-01-13 17:56 UTC, closed without merging