No-op Instruction analyzer
prysmaticlabs/prysm pull request #7249
Opened 2020-09-16 16:24 UTC by rkapka

**What type of PR is this?**

Tool

**What does this PR do? Why is it needed?**

This PR introduces a static code analyzer that reports a diagnostic when a no-op instruction (e.g. `*&`) has been found. Occurrences of such code in Prysm have been found here: https://deepsource.io/gh/rkapka/prysm/issue/SCC-SA4001/occurrences.

**Which issues(s) does this PR fix?**

Part of #6747

**Other notes for review**

N/A

2020-09-16 16:27 UTC, rkapka commented on shared/bls/herumi/signature_test.go
> +package herumi
I had to change this to be able to access `Signature.s`

2020-09-17 06:12 UTC, nisdas requested changes

2020-09-17 06:12 UTC, nisdas commented on shared/bls/herumi/signature_test.go
> +func TestCopy(t *testing.T) {
This doesn't test that it is a safe copy all it does check that the interface representation is not equal. Also 
the fact that after a copy the different signatures are not equal means that either the copy is bad or the 
interface equality action regards them as different when they are not. For values like these `DeepEqual` is 
more accurate.

2020-09-17 06:12 UTC, nisdas commented on shared/bls/herumi/signature_test.go
> +	require.Equal(t, true, ok)
to test it better you need to do `signatureA.s.Add(random_sig)` and then make sure sigA and sigB are unequal.

2020-09-17 10:51 UTC, nisdas submitted a review, later dismissed

2020-09-17 16:18 UTC, nisdas approved these changes

2020-09-17 16:18 UTC, merged