Fix Mismatched BlockRoots In State Replay
prysmaticlabs/prysm pull request #7559
Opened 2020-10-17 13:45 UTC by nisdas

**What type of PR is this?**

Bug Fix 

**What does this PR do? Why is it needed?**

- [x] During times without finality the database doesn't return the same number of blocks and its
respective roots in-order. This is especially true for unfinalized blocks. 

Follows on from #7019 and #7028  

**Which issues(s) does this PR fix?**

**Other notes for review**

2020-10-17 15:29 UTC, terencechain requested changes
Then the issue is on the block roots retrieval in db? Should we fix it on that end? Can we reproduce this with a DB test?

Not 100% sure about this because it feels like the real issue is getting masked away and we should fix it instead or at least open a tracking issue

2020-10-17 17:01 UTC, prestonvanloon reviewed
Please add regression test if possible

2020-10-18 14:57 UTC, nisdas commented
> Then the issue is on the block roots retrieval in db? Should we fix it on that end? Can we reproduce this with a DB test?

So there is a slight race with retrieval of roots and their respective blocks. In times of network turbulence, you could see occasionally the 2 calls retrieving differing results. We shouldn't be using it this way, as there is always a chance of a mismatch. What I could instead do is expose the Blocks API to return the roots also.

2020-10-18 15:28 UTC, prestonvanloon submitted a review, later dismissed

2020-10-18 15:33 UTC, terencechain approved these changes

2020-10-18 16:39 UTC, prestonvanloon approved these changes

2020-10-18 16:39 UTC, merged