return error properly
prysmaticlabs/prysm pull request #7678
Opened 2020-10-29 19:35 UTC by rauljordan

Part of #7410, this PR returns an error in `ProcessPreGenesisDeposits` if a pubkey for a deposit is not found in the beacon state. This is a good best practice as outlined by trail of bits. However, the conditional will never trigger because of how the function works:

1. Process all new deposits into the beacon state
2. Then, for each deposit that was processed, fetch the validator corresponding to the public key in the deposit

Since step (1) added new validators into the state before (2) runs, there will _always_ be a corresponding validator for a public key for each processed deposits. As such, it is impossible to write a test for this. However, we should still handle the error for consistency.

2020-10-29 19:43 UTC, terencechain approved these changes

2020-10-30 07:00 UTC, nisdas requested changes
This is not correct, we need to continue processing in the even if the validator does not exist. There is always the possibility of processing invalid deposits with bad pubkeys/signatures.

2020-11-02 15:52 UTC, shayzluf commented on beacon-chain/core/blocks/deposit_test.go
> +		t.Errorf("Expected validator list to have length 1, received: %v", len(newState.Validators()))
seems like you are expecting 100 not 1 as the comment mentions

2020-11-02 16:06 UTC, rauljordan commented on beacon-chain/core/blocks/deposit_test.go
> +		t.Errorf("Expected validator list to have length 1, received: %v", len(newState.Validators()))
```suggestion
		t.Errorf("Expected validator list to have length 100, received: %v", len(newState.Validators()))
```

2020-11-02 16:06 UTC, rauljordan commented on beacon-chain/core/blocks/deposit_test.go
> +		t.Errorf("Expected validator balances list to have length 1, received: %v", len(newState.Balances()))
```suggestion
		t.Errorf("Expected validator balances list to have length 100, received: %v", len(newState.Balances()))
```

2020-11-02 16:27 UTC, shayzluf approved these changes
Lgtm

2020-11-02 16:34 UTC, merged