Reduce Hashing When Filling In Forkchoice Blocks
prysmaticlabs/prysm pull request #7716
Opened 2020-11-03 14:41 UTC by nisdas

**What type of PR is this?**

Minor Cleanup

**What does this PR do? Why is it needed?**

- [x] Reduce redundant hashing and simply use already known roots for the respective blocks.

**Which issues(s) does this PR fix?**

N.A

**Other notes for review**

2020-11-03 14:49 UTC, terencechain requested changes
Can you add some tests? Thanks

2020-11-04 09:02 UTC, shayzluf reviewed
lgtm

2020-11-04 15:33 UTC, terencechain submitted a review, later dismissed

2020-11-04 18:38 UTC, farazdagi commented on beacon-chain/blockchain/process_block_test.go
> +
```suggestion
```

2020-11-04 18:38 UTC, farazdagi approved these changes

2020-11-05 01:33 UTC, merged