Add Pubkey Metrics To Measure Cache Miss and Hits
prysmaticlabs/prysm pull request #7897
Opened 2020-11-22 14:21 UTC by nisdas

**What type of PR is this?**

Feature Addition

**What does this PR do? Why is it needed?**

- [x] Adds in pubkey metrics to measure cache miss and hit ratios. In Pyrmont, sync was 50% slower
because our cache wasn't able to hold 100,000 validator pubkeys. Given the low-cost of it, having
a metric to measure hit and miss ratios is useful.

**Which issues(s) does this PR fix?**

N.A

**Other notes for review**

2020-11-22 14:28 UTC, shayzluf commented on shared/bls/herumi/public_key.go
> +
```suggestion
```

2020-11-22 14:31 UTC, shayzluf reviewed
- it will be nice to know the space left in cache 
- maybe we should already increase the maxKeys to handle pyrmont better

2020-11-22 14:31 UTC, shayzluf commented on shared/bls/blst/public_key.go
> +
```suggestion
```

2020-11-22 16:38 UTC, terencechain requested changes
Concern: Wouldn't this increase the cardinality of the metrics page significantly and require tsdb to store much more data than before?

2020-11-22 16:38 UTC, terencechain commented on shared/bls/blst/public_key.go
> +			Name: "blst_pubkey_cache_hit",
Please follow https://prometheus.io/docs/practices/naming/

2020-12-10 22:04 UTC, prestonvanloon commented
Any update on this?

2021-01-05 02:15 UTC, rauljordan commented
Any update on this one @nisdas ?

2021-01-05 06:17 UTC, nisdas commented
Not fully relevant now, given that we have a very large pubkey cache. Closing the PR @rauljordan

2021-01-05 06:17 UTC, closed without merging