Beacon-chain and Validator flag cleanup
prysmaticlabs/prysm pull request #7920
Opened 2020-11-23 00:51 UTC by 0xKiwi

**What type of PR is this?**
Cleanup

**What does this PR do? Why is it needed?**
This PR moves a lot of beacon-chain specific flags to the beacon-chain/flags package and separates them to be better organized.
Also does a similar process for the validator flags.

2020-11-23 01:03 UTC, terencechain commented on beacon-chain/flags/base.go
>  )
I recommend rename `base.go` to something more appropriate

2020-11-23 01:03 UTC, terencechain commented on validator/flags/base.go
> +	SlasherRPCProviderFlag = &cli.StringFlag{
this is RPC

2020-11-23 01:03 UTC, terencechain commented on validator/flags/base.go
> +	// SlasherCertFlag defines a flag for the slasher node's TLS certificate.
this is RPC

2020-11-23 01:03 UTC, terencechain commented on validator/flags/base.go
> +	DisableAccountMetricsFlag = &cli.BoolFlag{
this is account management

2020-11-23 01:03 UTC, terencechain commented on validator/flags/base.go
> +	DisablePenaltyRewardLogFlag = &cli.BoolFlag{
this is account management

2020-12-02 17:50 UTC, prestonvanloon requested changes

2020-12-02 17:50 UTC, prestonvanloon commented on beacon-chain/flags/p2p.go
> +		Usage: "Enable the service (Beacon chain or Validator) to use UPnP when possible.",
Validator does not use this flag! (I hope)

2020-12-02 17:50 UTC, prestonvanloon commented on beacon-chain/flags/rpc.go
> +		Usage: "Host on which the RPC server should listen",
```suggestion
		Usage: "Host on which the gRPC server should listen",
```

2020-12-02 17:50 UTC, prestonvanloon commented on beacon-chain/flags/rpc.go
> +		Usage: "A mainchain web3 provider string http endpoint",
```suggestion
		Usage: "An eth1 web3 provider string http endpoint",
```

2020-12-02 17:50 UTC, prestonvanloon commented on beacon-chain/flags/rpc.go
> +		Usage: "RPC port exposed by a beacon node",
```suggestion
		Usage: "gRPC port exposed by a beacon node",
```

2020-12-02 17:50 UTC, prestonvanloon commented on beacon-chain/flags/rpc.go
> +		Usage: "The host on which the gateway server runs on",
```suggestion
		Usage: "The host on which the gateway server runs on to serve JSON-HTTP requests",
```

2020-12-02 17:50 UTC, prestonvanloon commented on beacon-chain/flags/rpc.go
> +		Usage: "Enable gRPC gateway for JSON requests",
```suggestion
		Usage: "The port on which the gateway server runs to serve JSON-HTTP requests",
```

2020-12-02 17:50 UTC, prestonvanloon commented on beacon-chain/flags/rpc.go
> +			"(browser enforced). This flag has no effect if not used with --grpc-gateway-port.",
This flag definitely has effect if used without changing --grpc-gateway-port.

```suggestion
			"(browser enforced).",
```

2020-12-02 17:50 UTC, prestonvanloon commented on shared/cmd/flags.go
> +		Usage: "Enable p2p message tracing.",
This isn't limited to p2p. 
```suggestion
		Usage: "Enable process tracing via OpenTracing / Jaeger exporter.",
```

2020-12-02 17:50 UTC, prestonvanloon commented on shared/cmd/flags.go
>  		Usage: "Tracing endpoint defines where beacon chain traces are exposed to Jaeger.",
```suggestion
		Usage: "Tracing endpoint defines where beacon chain traces are pushed to a OpenTracing/Jaeger collector.",
```

2020-12-02 17:50 UTC, prestonvanloon commented on shared/cmd/flags.go
>  		Usage: "Indicate what fraction of p2p messages are sampled for tracing.",
```suggestion
		Usage: "Indicate what fraction of p2p messages are sampled for tracing. On scale of 0 to 1.0.",
```

2020-12-02 17:50 UTC, prestonvanloon commented on validator/flags/account.go
> +	}
What is this used for? Prysm doesn't send deposit to deposit contract?

This flag is only used here: https://github.com/prysmaticlabs/prysm/blob/f75a8efc0d6584233dd6f1e4c6d40d5493355c70/validator/accounts/wallet_create.go#L128

Please fix appropriately.

2020-12-02 18:00 UTC, redblaze4209 approved these changes

2020-12-02 18:01 UTC, redblaze4209 approved these changes

2020-12-02 18:01 UTC, redblaze4209 approved these changes

2020-12-19 07:07 UTC, closed without merging