Penalize Bad SSZ Payloads Correctly
prysmaticlabs/prysm pull request #7926
Opened 2020-11-23 15:50 UTC by nisdas

**What type of PR is this?**

Networking Cleanup

**What does this PR do? Why is it needed?**

- [x] Penalize peer if they send bad payload over the wire.
- [x] Add unit test for it.

**Which issues(s) does this PR fix?**

Fixes #

**Other notes for review**

2020-11-23 17:21 UTC, prestonvanloon commented on beacon-chain/sync/rpc.go
> +				if strings.Contains(topic, p2p.RPCGoodByeTopic) {
What about the status topic? That seems to be a logic change here.

2020-11-23 17:33 UTC, prestonvanloon requested changes
Discussed offline that we'd like to evaluate this a feature a bit more. There is a risk that non-ssz issues could end up banning peers unnecessarily. Given the time constraints for v1, we'll push this feature into v1.1 release target.

2020-12-10 22:05 UTC, prestonvanloon commented
Any update on this?

2020-12-11 11:14 UTC, nisdas commented
Will leave this on for v1.06 @prestonvanloon , I want to limit the amount of networking changes we push out to v1.05 for the week. A lot of big PRs are to be merged soon in v1.05 .

2021-01-05 02:16 UTC, rauljordan commented
Should we still target this one for v1.0.6?

2021-01-05 06:16 UTC, nisdas commented
@rauljordan Maybe 1.07 might be better for this, we have too many PRs now in 1.05 anyway. This also is a bit of a non trivial change to apply to the network might be better to have a bit more testing for it.

2021-07-12 15:49 UTC, prestonvanloon commented
What can we do to merge this? Can we put it behind a feature flag?

Given that this PR has been open for 8 months, we should merge or close it this week. The stale bot will keep applying the label otherwise.

2021-08-03 03:06 UTC, closed without merging