Att check max epochs 1
prysmaticlabs/prysm pull request #7966
Opened 2020-11-26 05:42 UTC by terencechain

**What type of PR is this?**

> Feature

**What does this PR do? Why is it needed?**

Review and merge #7965 first

This PR adds the following eip-3076 checks to `preAttSignValidations` and updates the lowest source and target epochs in `postAttSignUpdate`

```
Refuse to sign any attestation with source epoch less than the minimum source epoch present in that signer’s attestations

Refuse to sign any attestation with target epoch less than or equal to the minimum target epoch present in that signer’s attestations
```

**Which issues(s) does this PR fix?**

Fixes #

**Other notes for review**

2020-11-26 12:02 UTC, nisdas approved these changes
LGTM too

2020-11-26 12:05 UTC, nisdas requested changes
Sorry rejecting this 
```
time="2020-11-26 05:59:00" level=error msg="Failed attestation slashing protection check" error="could not sign attestation lower than lowest target epoch in db, 0 >= 0" prefix=validator pubKey=0xb3eea1ef03b3 slot=0
time="2020-11-26 05:59:00" level=error msg="Failed attestation slashing protection check" error="could not sign attestation lower than lowest target epoch in db, 0 >= 0" prefix=validator pubKey=0xa626ce67a47d slot=0
```

2020-11-26 16:45 UTC, nisdas submitted a review, later dismissed

2020-11-26 16:59 UTC, prestonvanloon commented on validator/client/attest_protect_test.go
> +		gomock.Any(), // epoch
Can you specify the value here? What do you expect to be sent? It looks like 0, which is a default value. Also consider a non-default value to make this test more robust.

2020-12-04 23:39 UTC, rauljordan approved these changes

2020-12-05 03:08 UTC, merged