Need to call backup after startDB in order for the handler to not pas…
prysmaticlabs/prysm pull request #8099
Opened 2020-12-12 01:24 UTC by Cipioo

…s nil.

**What type of PR is this?**

> Uncomment one line below and remove others.
>
Bug fix
> Feature
> Documentation
> Other

**What does this PR do? Why is it needed?**
It creates the backup handler after the db is started. This is needed in order for the handler to not be passed nil, which causes Slasher DB Backup to fail.
**Which issues(s) does this PR fix?**
8070
Fixes #

**Other notes for review**

2020-12-12 01:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prysmaticlabs/prysm?pullRequest=8099) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prysmaticlabs/prysm?pullRequest=8099) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prysmaticlabs/prysm?pullRequest=8099) it.</sub>

2020-12-12 03:07 UTC, Dour420 requested changes
Violation of privacy

2020-12-12 21:59 UTC, Grubson33421 approved these changes

2020-12-12 22:00 UTC, Grubson33421 approved these changes

2020-12-14 08:38 UTC, nisdas approved these changes
Thanks !

2020-12-14 21:39 UTC, merged