Configurable Interval for Debouncing Keystore Reloading in Validator Client
prysmaticlabs/prysm pull request #8149
Opened 2020-12-17 16:35 UTC by rauljordan

No tracking issue. This feature adds the ability to configure the debounce interval used in the validator client to detect changes to keystores in the wallet on disk. Making it easier to import large chunks of keystores into the validator client dynamically without it triggering a reload every second. The flag is:

```
--dynamic-key-reload-debounce-interval
```
Measured in seconds and with a default value of 1.

2020-12-17 23:23 UTC, rkapka commented
My understanding, taken from a few Discord discussions, is that we don't want to flood users with flags. If this is right, is this flag worth adding? If I import a thousand keystores, does it have a negative effect on the validator other than outputting a bunch of logs? Also, this scenario is probably pretty unlikely.

2021-01-04 18:52 UTC, prestonvanloon requested changes
Using a DurationFlag removes the ambiguity of time units and allows for more flexible configuration.

Users could do `--dynamic-key-reload-debounce-interval=1s` or `--dynamic-key-reload-debounce-interval=1500ms` which is more clear than `--dynamic-key-reload-debounce-interval=1.5`.

2021-01-04 18:52 UTC, prestonvanloon commented on shared/featureconfig/config.go
> +	KeystoreImportDebounceInterval int
What about making this a time.Duration?

2021-01-04 18:52 UTC, prestonvanloon commented on shared/featureconfig/config.go
> +	cfg.KeystoreImportDebounceInterval = ctx.Int(dynamicKeyReloadDebounceInterval.Name)
We can use ctx.Duration and have dynamicKeyReloadDebounceInterval to be a DurationFlag. 

https://pkg.go.dev/github.com/urfave/cli/v2#Context.Duration

2021-01-04 18:52 UTC, prestonvanloon commented on shared/featureconfig/flags.go
> +	dynamicKeyReloadDebounceInterval = &cli.IntFlag{
DurationFlag

2021-01-04 23:18 UTC, rauljordan commented
Excellent suggestion, thank you

2021-01-04 23:20 UTC, prestonvanloon approved these changes

2021-01-05 00:52 UTC, merged