[Feature] - Optimized Slasher Refactor
prysmaticlabs/prysm pull request #8340
Opened 2021-01-26 18:02 UTC by rauljordan

Part of #8331, this PR is a feature branch containing all action items specified in the tracking issue for refactoring our slasher

2021-04-22 16:52 UTC, terencechain submitted a review, later dismissed

2021-04-22 18:15 UTC, farazdagi reviewed
Absolutely astonishing amount of work (explanatory comments are epitome of self-documenting code)!

2021-04-22 18:15 UTC, farazdagi commented on beacon-chain/slasher/chunks.go
> +
```suggestion
//
```

2021-04-22 18:15 UTC, farazdagi commented on beacon-chain/slasher/helpers.go
> +		if attWrapper.IndexedAttestation.Data.Source.Epoch+types.Epoch(s.params.historyLength) <= currentEpoch {
```suggestion
		if attWrapper.IndexedAttestation.Data.Source.Epoch+s.params.historyLength <= currentEpoch {
```
`historyLength` is of `Epoch` type.

2021-04-23 06:28 UTC, nisdas requested changes

2021-04-23 06:28 UTC, nisdas commented on beacon-chain/blockchain/process_block.go
> +				indexedAtt, err := attestationutil.ConvertToIndexed(ctx, att, committee)
you should probably use another context given that its an async method which might be expensive.

2021-04-23 06:28 UTC, nisdas commented on beacon-chain/blockchain/receive_attestation.go
> +func (s *Service) AttestationTargetState(ctx context.Context, attTarget *ethpb.Checkpoint) (iface.BeaconState, error) {
Changes like this might be better suited in another PR. They are general enough and can reduce the overall PR delta.

2021-04-23 06:28 UTC, nisdas commented on beacon-chain/blockchain/service.go
> +	WspEpoch                types.Epoch
+1

2021-04-23 06:28 UTC, nisdas commented on beacon-chain/core/blocks/signature.go
> +func VerifyBlockHeaderSignature(beaconState iface.BeaconState, header *ethpb.SignedBeaconBlockHeader) error {
This too, another PR is fine for this.

2021-04-23 06:28 UTC, nisdas commented on beacon-chain/node/node.go
> -	if err := b.db.EnsureEmbeddedGenesis(b.ctx); err != nil {
please add this back

2021-05-20 16:23 UTC, rauljordan commented
@nisdas PTAL

2021-06-07 15:52 UTC, prestonvanloon commented
What's the status on this PR? Thanks

2021-06-17 20:02 UTC, rauljordan commented
Ready again @nisdas

2021-08-05 16:02 UTC, rauljordan commented
Blocking merge until we are ready for a v2 release

2021-09-30 02:33 UTC, closed without merging