Add Programmatic Voluntary Exits
prysmaticlabs/prysm pull request #8399
Opened 2021-02-04 20:49 UTC by rauljordan

**What does this PR do? Why is it needed?**

Currently, validators cannot submit voluntary exits without manually entering a confirmation via the command line. This PR adds a flag `--skip-voluntary-exit-confirmation` to accomplish this.

**Which issues(s) does this PR fix?**

Fixes #8383

2021-02-04 21:09 UTC, terencechain submitted a review, later dismissed

2021-02-04 22:18 UTC, rkapka reviewed
From the issue:

> So basically one command to request exit for all validators at the same time. Maximum a yes/no question but perhaps not even that. The ones who looks up and executes this command surely knows he is about to exit all validators wether its 1 x 32ETH or 500 x 32ETH instantly.

I think what this means is an option to exit all validators without even having to select anything. Just type the command, maybe display a yes/no confirmation and exit everything. Do we want to support that? It's risky.

2021-02-04 22:22 UTC, rkapka submitted a review, later dismissed
Blocking the PR for now as I don't think this fixes the issue, as this is not what OP wants.

2021-02-04 22:32 UTC, makultar commented
> Comment from the issue's creator @makultar:
> 
> > So basically one command to request exit for all validators at the same time. Maximum a yes/no question but perhaps not even that. The ones who looks up and executes this command surely knows he is about to exit all validators wether its 1 x 32ETH or 500 x 32ETH instantly.
> 
> I think what this means is an option to exit all validators without even having to select anything. Just type the command, maybe display a yes/no confirmation and exit everything. Do we want to support that? It's risky.

> Blocking the PR for now as I don't think this fixes the issue, as this is not what OP wants.
Holddddddd your horses! 

I think something like _--skip-voluntary-exit-confirmation_ is exactly was I am looking for. Or at least on the right path. 

Hmm I dont agree with "Its risky". Staking itself is already risky, i.e depositing 50 000 USD+, making sure the system works flawlessly, that you dont get hacked, making sure your mnemonic is with you x years while withdrawal is disabled etc etc. There is just tons of various risks. Making an exit to keep your funds safe surely is not. Then lets make sure its well described and with several warnings around that description?

No one is dumb enough to execute a command thats wrapped around
*** WARNING * WARNING * WARNING * WARNING * WARNING * WARNING *** 
*** THE FOLLOWING COMMAND WILL EXIT ALL YOUR VALIDATORS AT ONCE ***
*** WARNING * WARNING * WARNING * WARNING * WARNING * WARNING *** 
There is no real risk. If you read this WARNING, and still decide to go ahead with a: YES -- thats on you. We are adult, not kids.

2021-02-05 04:07 UTC, makultar commented
> Comment from the issue's creator @makultar:
> 
> > So basically one command to request exit for all validators at the same time. Maximum a yes/no question but perhaps not even that. The ones who looks up and executes this command surely knows he is about to exit all validators wether its 1 x 32ETH or 500 x 32ETH instantly.
> 
> I think what this means is an option to exit all validators without even having to select anything. Just type the command, maybe display a yes/no confirmation and exit everything. Do we want to support that? It's risky.

> Blocking the PR for now as I don't think this fixes the issue, as this is not what OP wants.

Holddddddd your horses! 

I think something like _--skip-voluntary-exit-confirmation_ is exactly was I am looking for. Or at least on the right path. 

Hmm I dont agree with "Its risky". Staking itself is already risky, i.e depositing 50 000 USD+, making sure the system works flawlessly, that you dont get hacked, making sure your mnemonic is with you x years while withdrawal is disabled etc etc. There is just tons of various risks. Making an exit to keep your funds safe surely is not. Very much the opposite. Then lets make sure its well described and with several warnings around that description so no one else can be blamed?

No one is dumb enough to execute a command thats wrapped around

*** **WARNING * WARNING * WARNING * WARNING * WARNING * WARNING** *** 
_*       THE FOLLOWING COMMAND WILL EXIT ALL YOUR VALIDATORS AT ONCE        *_
*** **WARNING * WARNING * WARNING * WARNING * WARNING * WARNING*** **

There is no real risk. If you read this WARNING x 12, and still decide to go ahead with a: YES -- thats on you. We are adults, not kids. Who is there to protect? I doubt there is kids or adults with severe brain damage staking 50k that dont know what they are doing :P

Edit: Typos hehe

2021-02-05 06:46 UTC, rkapka commented
Copying from Discord:

IIRC, right now you have to manually enter all keys that you want to exit. accounts delete has this nice dropdown that you can choose from, with an Select all option. Maybe we can utilize that, combined with the flag that you introduced?

2021-02-05 12:04 UTC, makultar commented
> Copying from Discord:
> 
> IIRC, right now you have to manually enter all keys that you want to exit. `accounts delete` has this nice dropdown that you can choose from, with an `Select all` option. Maybe we can utilize that, combined with the flag that you introduced?

I would be very happy if the following command was possible
`/usr/local/bin/validator accounts voluntary-exit --wallet-dir=/var/lib/prysm/validator _--select-all --skip-voluntary-exit-confirmation_`

**Letting you only confirm with a yes/no:**
*** **WARNING * WARNING * WARNING * WARNING * WARNING * WARNING** *** 
_*       THE FOLLOWING COMMAND WILL EXIT ALL YOUR VALIDATORS AT ONCE        *_
_*                                            ARE YOU SURE? Yes/No                                                  *_
*** **WARNING * WARNING * WARNING * WARNING * WARNING * WARNING*** **

=> Exits

2021-02-05 12:07 UTC, makultar commented
For someone thats not a techie, like my family, wife, or future kids. I dont want this to be a complicated task or menu. My instructions to them will be very simply.

1. Login into server 127.0..1
2. Copypaste and press enter: 
3. /usr/local/bin/validator accounts voluntary-exit --wallet-dir=/var/lib/prysm/validator _ --select-all --skip-voluntary-exit-confirmation _
4. Type "Yes" => Enter

2021-02-05 12:08 UTC, makultar commented
For someone thats not a techie, like my family, wife, or future kids. I dont want this to be a complicated task or menu. My instructions to them will be very simply.

1. Login into server 127.0..1
2. Copypaste and press enter: 
/usr/local/bin/validator accounts voluntary-exit --wallet-dir=/var/lib/prysm/validator **--select-all --skip-voluntary-exit-confirmation**
3. Type "Yes" when asked to confirm => Enter

Not a long restaurant menu going through all kinds of options, opening up for real real problems.

2021-02-05 17:08 UTC, rauljordan commented
Thanks @makultar totally understand your rationale now. All you want is a simple command that allows you specify you want to exit all public keys via a flag, then a simple confirmation that looks scary, and then you're done. We agree this is an important feature to safeguard your eth in case something happens to you and a family member needs to perform the action, thank you for bringing it to our attention, we will amend to do as you requested

2021-02-05 21:48 UTC, makultar commented
> Thanks @makultar totally understand your rationale now. All you want is a simple command that allows you specify you want to exit all public keys via a flag, then a simple confirmation that looks scary, and then you're done. We agree this is an important feature to safeguard your eth in case something happens to you and a family member needs to perform the action, thank you for bringing it to our attention, we will amend to do as you requested

Wow thats great! Thanks a ton for this. Cool and kind of you guys. I will launch a few testnet validators and test this feature for sure.

2021-02-06 14:40 UTC, rkapka requested changes
Please test the new functionality.

2021-02-06 14:40 UTC, rkapka commented on validator/accounts/accounts_exit.go
> +		fmt.Printf("About to perform a voluntary exit of %d accounts\n", len(rawPubKeys))
This needs a test.

2021-02-08 20:53 UTC, rauljordan commented
Done @rkapka

2021-02-10 20:25 UTC, rauljordan commented
Ready again @rkapka

2021-02-11 07:08 UTC, rkapka approved these changes
Looks great, thanks!

2021-02-11 16:50 UTC, merged