Graffiti ordered index
prysmaticlabs/prysm pull request #8482
Opened 2021-02-20 15:48 UTC by qix

**What type of PR is this?**

> Feature

**What does this PR do? Why is it needed?**

This is based on top of #8189 by @pinglamb. I extended it so that instead of resetting upon validator restart the index is stored in the database. Alongside it I store a hash of the graffiti file so that the index can be reset whenever the file is updated.

**Which issues(s) does this PR fix?**

Fixes #8181 #8189

**Other notes for review**

I left the behavior of cycling through the graffiti untouched, however I think it would be better if each was only emitted once. That way `ordered` could be combined with `random`/`default` which would take effect once all the ordered entries have been emitted.

2021-02-20 15:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prysmaticlabs/prysm?pullRequest=8482) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/prysmaticlabs/prysm?pullRequest=8482) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: pinglamb<br/>:x: qix<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prysmaticlabs/prysm?pullRequest=8482) it.</sub>

2021-02-21 19:42 UTC, rkapka commented
@qix  `bazel run //:gazelle -- fix` is needed to fix dependencies. Otherwise the build will keep failing.

2021-02-21 21:24 UTC, qix commented
> @qix `bazel run //:gazelle -- fix` is needed to fix dependencies. Otherwise the build will keep failing.
> 
> And of course thank you for the contribution, my friend!

Thanks! Might be worth mentioning that in the `CONTRIBUTING` doc. Just ran it and the only thing I missed was ordering in one of the BUILD fles

2021-02-22 15:13 UTC, rauljordan commented on validator/db/kv/graffiti.go
> +	err := s.db.Update(func(tx *bolt.Tx) error {
Small thing not necessary to fix, but can be simplified to `return s.db.Update`

2021-02-22 15:13 UTC, rauljordan submitted a review, later dismissed
Nice job and unit tests!

2021-02-22 15:18 UTC, terencechain requested changes
Looks like @prestonvanloon has concerns about saving graffiti index to DB.

Let's have him take one last look before merging

https://github.com/prysmaticlabs/prysm/pull/8189#discussion_r562089786

2021-02-23 16:33 UTC, rauljordan commented
Please take a look at conflicts @qix. Once resolved, you will also need to run `bazel run //:gazelle -- fix`

2021-02-23 18:27 UTC, qix commented
Rebased

The concerns @prestonvanloon raised were about how the index might be reset which I believe this solves (by tying it directly to the hash of the graffiti source). I'll wait for the okay from him though.

2021-02-24 21:13 UTC, prestonvanloon approved these changes
The design of this looks good. I'm happy with the solution. Raul had a suggestion, but I approve

2021-02-24 22:14 UTC, qix commented
Thanks @prestonvanloon.

Sorry I'm not entirely used to this workflow, I included the fix Raul gave and rebased on top of master but that dismissed your approval. It looks like I'll need another stamp from @terencechain as well since they requested changes.

2021-02-24 22:28 UTC, terencechain approved these changes

2021-02-24 22:50 UTC, merged

2021-02-24 22:55 UTC, qix commented
Awesome! Thanks a lot for the pleasant review y'all :)

Hopefully you'll see a bit more from me in the future.