Add Spans To Attestation Caches
prysmaticlabs/prysm pull request #8556
Opened 2021-03-04 13:58 UTC by nisdas

**What type of PR is this?**

Monitoring

**What does this PR do? Why is it needed?**

- [x] Adds spans for a few methods in our attestation caches as they are directly in the hot path of our aggregator.

**Which issues(s) does this PR fix?**

N.A

**Other notes for review**

2021-03-04 15:14 UTC, terencechain approved these changes

2021-03-04 15:25 UTC, prestonvanloon requested changes

2021-03-04 15:25 UTC, prestonvanloon commented on beacon-chain/operations/attestations/kv/aggregated.go
> +	return c.aggregateUnaggregatedAttestations(context.Background(), unaggregatedAtts)
This will make tracking these spans impossible in the full context of the operation. Please use a parent context of some kind.

2021-03-05 14:37 UTC, prestonvanloon approved these changes

2021-03-05 15:17 UTC, merged