Invert BLST Go Tag
prysmaticlabs/prysm pull request #8725
Opened 2021-04-08 13:51 UTC by nisdas

**What type of PR is this?**

Cleanup

**What does this PR do? Why is it needed?**

**Which issues(s) does this PR fix?**

Fixes #

**Other notes for review**

2021-04-08 13:58 UTC, rauljordan submitted a review, later dismissed

2021-04-08 14:39 UTC, rauljordan approved these changes

2021-04-10 15:16 UTC, farazdagi requested changes

2021-04-10 15:16 UTC, farazdagi commented on shared/bls/blst/BUILD.bazel
> +#  Build with --define=blst_disabled=false to exclude blst library.
```suggestion
#  Build with --define=blst_disabled=true to exclude blst library.
```

2021-04-11 10:58 UTC, farazdagi approved these changes

2021-04-11 11:11 UTC, merged