Use Binary Search To Retrieve Validator Instead of HashMap
prysmaticlabs/prysm pull request #8854
Opened 2021-05-02 13:40 UTC by nisdas

**What type of PR is this?**

Feature Cleanup

**What does this PR do? Why is it needed?**

- [x] In early testnets we utilized a validator map to keep track of all validator pubkeys and their respective indices. However with the current growth in mainnet state, maintaing a map is very expensive on memory with our current beacon state model and the benefits are arguably not worth it. This PR will increase the time complexity of retrieving validators from `O(1)` to `O(log n)` . However the benefits on memory usage make this change more than worth it, as it completely removes memory spikes at an increased cost of processing blocks with deposits.

**Which issues(s) does this PR fix?**

Fixes #8483 

**Other notes for review**

2021-05-02 14:44 UTC, rkapka reviewed
Can you write some tests?

2021-05-02 14:44 UTC, rkapka commented on beacon-chain/state/stateV0/getters_validator.go
> +	for i := numOfVals - 1; i >= 0; i-- {
This function is very general and has a lot of usages, some of which might prefer the search to be frontwards. I understand that backwards iteration is helpful for deposits, but won't it make other usages slower? I think we should prefer idiomatic iteration unless there's a strong reason not to.

2021-05-02 22:34 UTC, prestonvanloon commented on beacon-chain/state/stateV0/getters_validator.go
> +	for i := numOfVals - 1; i >= 0; i-- {
This performance trade off seems off. If the set is getting so big that we can't maintain a map in memory, won't O(n) be really poor performance?

2021-05-02 22:36 UTC, prestonvanloon requested changes
Can you add supporting evidence to the memory claim and evidence to show the trade off is reasonable?

2021-05-03 00:40 UTC, nisdas commented
@prestonvanloon 

Attached is a heap profile during deposit processing. Most of the increased memory usage comes about due to map copies performed. Even if you shift down to O(n) there is no cost in accessing validators in memory for deposit processing, unlike now where that is not the case since we copy on write.

[heap.tar.gz](https://github.com/prysmaticlabs/prysm/files/6412518/heap.tar.gz)

I will be looking to see if there are other more tenable solutions we can take.

2021-05-03 02:27 UTC, potuz commented
I am a bit worried about the trade here: we're trading possible context deadlines because of constrained environments to risking missing a proposal because of not being able to process deposits on time. This would have to be carefully benchmarked on testnets under heavy deposits times.

2021-05-05 14:54 UTC, nisdas commented
Superseded by #8860

2021-05-05 14:54 UTC, closed without merging