Graffiti hex support
prysmaticlabs/prysm pull request #8894
Opened 2021-05-14 19:08 UTC by d00medman

**What type of PR is this?**
Feature

**What does this PR do? Why is it needed?**
When a user provides a string prefixed with "hex:" followed by a hexidecimal string, this change will cause that piece of graffiti to be converted to ascii characters. It was deemed a reasonable feature for the system to have 

**Which issues(s) does this PR fix?**

Fixes #8168 

**Other notes for review**
Performs the conversion to ascii at startup; original value of yaml file captured by the hash field of the graffiti struct. Opted to make conversion errors non-blocking, when this happens the graffiti will be "hex:whatever"

2021-05-17 08:12 UTC, rkapka requested changes

2021-05-17 08:12 UTC, rkapka commented on validator/graffiti/parse_graffiti_test.go
> +			name:  "unsupported hex 2",
I think we should support `0x` prefixes.

2021-05-17 08:12 UTC, rkapka commented on validator/graffiti/parse_graffiti_test.go
> +			name:  "irregular hex 1",
Can you provide a more descriptive name?

2021-05-17 08:12 UTC, rkapka commented on validator/graffiti/parse_graffiti_test.go
> +			name:  "irregular hex 1",
Can you provide a more descriptive name?

2021-05-17 08:12 UTC, rkapka commented on validator/graffiti/parse_graffiti_test.go
> +			require.Equal(t, out, tt.want)
We usually use the `require` package for assertions which are required to pass before a test can continue. In normal circumstances we use `assert`.

2021-05-17 08:12 UTC, rkapka commented on validator/graffiti/parse_graffiti.go
> +	g.Random = parseGraffitiStrings(g.Random)
I'm not sure what's going on here. Can you explain this piece of code?

2021-05-17 08:22 UTC, rkapka commented
> Opted to make conversion errors non-blocking, when this happens the graffiti will be "hex:whatever"

This doesn't seem to be covered by any test case. Also I am not that big of a fan of `whatever`. I would prefer leaving the graffiti empty or providing something more meaningful like `[parse error]`. I don't have a strong opinion on this one, though.

2021-05-17 08:23 UTC, rkapka commented on validator/graffiti/parse_graffiti_test.go
> +
I'm happy that this `TODO` worked for you.

2021-05-17 14:12 UTC, d00medman commented
> > Opted to make conversion errors non-blocking, when this happens the graffiti will be "hex:whatever"
> 
> This doesn't seem to be covered by any test case. Also I am not that big of a fan of `whatever`. I would prefer leaving the graffiti empty or providing something more meaningful like `[parse error]`. I don't have a strong opinion on this one, though.

So the "whatever" isn't actually what you'll get as an output, I just used it as a stand in. For example, if you put "hex:test 123", the graffiti used by the validator will be "hex:test 123", apologies for the lack of clarity here

2021-05-21 06:12 UTC, rkapka requested changes

2021-05-21 06:12 UTC, rkapka commented on validator/graffiti/parse_graffiti.go
> +			if target[:2] == "0x" {
The two conditionals can be merged with `&&`

2021-05-21 06:13 UTC, rkapka commented
You need to run `bazel run //:gazelle -- fix` to make the build happy. This will update package dependencies.

2021-05-24 16:49 UTC, rauljordan commented on validator/graffiti/parse_graffiti.go
> +			log.Debug("Nothing after 0x prefix, hex tag to be interpreted as itself")
You can use WithField to show us what this graffiti is. It could be helpful for end users

2021-05-24 16:49 UTC, rauljordan commented on validator/graffiti/parse_graffiti.go
> +	if strings.ToLower(splitGraffiti[0]) == "hex" {
For maintenance purposes, it is easier to refactor this "magic" string to the top of the file as a variable, perhaps something called "hexGraffitiPrefixKey"

2021-05-25 18:45 UTC, rauljordan submitted a review, later dismissed

2021-05-25 18:53 UTC, rauljordan commented
PTAL @rkapka

2021-05-27 21:53 UTC, 0xKiwi commented
E2E is currently failing with the following error:
```
    assertions.go:85: endtoend_test.go:221 Evaluation failed for epoch 1: could not get graffiti from the list: could not get graffiti from the list
    ```

2021-05-28 15:28 UTC, prestonvanloon requested changes
Please address e2e failure

2021-05-28 15:28 UTC, prestonvanloon commented on validator/graffiti/parse_graffiti_test.go
>    703727: Meow`)
Please don't change an existing test. This previous logic should still behave the same. Add a new test for `hex:` prefixed strings.

2021-06-03 02:22 UTC, rndstr reviewed
just some drive-by nits, feel free to ignore

2021-06-03 02:22 UTC, rndstr commented on validator/graffiti/parse_graffiti.go
> +	hexGraffitiPrefixKey = "hex"
nit: could just be `hexGraffitiPrefix` (it's either a key or a prefix, no need for both)

2021-06-03 02:22 UTC, rndstr commented on validator/graffiti/parse_graffiti.go
> +	if strings.ToLower(splitGraffiti[0]) == hexGraffitiPrefixKey {
nit: early return for readability:

```
if strings.ToLower(splitGraffiti[0]) != hexGraffitiPrefixKey {
    return rawGraffiti
}
```

2021-06-03 02:22 UTC, rndstr commented on validator/graffiti/parse_graffiti.go
> +			log.WithFields(logrus.Fields{
nit: for single field could just use `log.WithField("graffiti", rawGraffiti).Debu...`

2021-06-09 15:56 UTC, prestonvanloon commented
Looks like some build failures:
> validator/graffiti/parse_graffiti.go:64:42: undefined: hexGraffitiPrefixKey

2021-06-09 19:56 UTC, d00medman commented
It is unclear to me why the e2e test is failing; eyeball test alone is not doing the trick. I have thus far been unsuccessful in running this suite locally, any help in doing so would be very helpful.

2021-06-09 20:16 UTC, prestonvanloon commented
Its failing to write the correct graffiti. You also have unit test failures. I imagine that if you fix the issues causing failures in the unit test, then you'll also fix the issue in the e2e tests.

2021-06-09 20:18 UTC, prestonvanloon commented
E2E is failing for this error
>     assertions.go:85: endtoend_test.go:221 Evaluation failed for epoch 1: could not get graffiti from the list: could not get graffiti from the list

2021-06-09 20:21 UTC, prestonvanloon commented
The e2e test is supposed to use a random graffiti, and i see that this block had no graffiti.

```
time="2021-06-09 16:50:41" level=info msg="Submitted new block" blockRoot=0x5b303b82d7ec graffiti="\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00" numAttestations=4 numDeposits=0 prefix=validator pubKey=0x87bbd5574c17 slot=1
```

2021-06-09 20:23 UTC, prestonvanloon commented
Without changing the unit tests, if you can make all of `TestParseGraffitiFile_*` pass, then I believe e2e should pass as well. There are multiple test failures there when parsing a graffiti file.

2021-06-10 14:54 UTC, prestonvanloon approved these changes
Amazing work! Thanks so much

2021-06-10 16:54 UTC, rkapka approved these changes

2021-06-10 16:54 UTC, merged