Trim SSE event names.
prysmaticlabs/prysm pull request #9342
Opened 2021-08-07 08:05 UTC by mcdee

**What type of PR is this?**

Bug fix

**What does this PR do? Why is it needed?**

When sending SSE events the event name contains trailing whitespace.  This patch removes the whitespace before processing the event, ensuring it is easily parsed by clients.

2021-08-07 11:52 UTC, rkapka requested changes
Thanks for the PR. I have one small request.

2021-08-07 11:52 UTC, rkapka commented on beacon-chain/rpc/apimiddleware/custom_handlers_test.go
> +		Event: []byte("test_event "),
Please a separate test named something like `TestWriteEvent_WhitespaceRemoved`.

2021-08-07 20:36 UTC, mcdee commented on beacon-chain/rpc/apimiddleware/custom_handlers_test.go
> +		Event: []byte("test_event "),
Updated.

2021-08-08 12:21 UTC, rkapka commented
For some reason the new test does not pass.

2021-08-08 13:17 UTC, mcdee commented
I took another look and changed the test to use `receiveEvents` rather than `writeEvent` as the base.  `receiveEvents` is the only place that calls `writeEvent`, and the logic to trim the event is up in `receiveEvents`so that's where it makes sense to inject the event with the trailing space.

2021-08-09 23:41 UTC, rauljordan commented
PTAL @rkapka

2021-08-11 17:42 UTC, rkapka approved these changes

2021-08-11 23:00 UTC, merged