Altair Committee Cache Changes
prysmaticlabs/prysm pull request #9366
Opened 2021-08-11 17:52 UTC by rauljordan

This PR adds changes from `beacon-chain/cache` in the `hf1` branch into `develop`, which are necessary for various helpers for the Altair hard fork. This adds committee cache active balance changes

2021-08-11 17:52 UTC, rauljordan commented on beacon-chain/cache/sync_subnet_ids.go
> +// assingments for epochs that have happened.
```suggestion
// assignments for epochs that have happened.
```

2021-08-11 18:07 UTC, terencechain commented on beacon-chain/cache/committee.go
> +	if !item.ActiveBalance.Exist {
We should test this block

2021-08-11 18:07 UTC, terencechain commented on beacon-chain/cache/committee_test.go
> +
We should add a test where 
```go
balances := &Balance{
		Exist: false,
	}
```

`ActiveBalance` should return `ErrNonCommitteeKey`

2021-08-11 18:58 UTC, terencechain submitted a review, later dismissed

2021-08-11 19:20 UTC, prestonvanloon commented on beacon-chain/cache/sync_subnet_ids.go
> -	// Index 1 and beyond were used to store subnets.
Why are many of these comments removed?

2021-08-11 19:22 UTC, prestonvanloon requested changes
It seems like this PR is undoing some of the feedback from #9350 with regards to commentary.

2021-08-11 19:36 UTC, prestonvanloon commented on beacon-chain/cache/committee.go
> +	if item == nil {
Can we check that item.ActiveBalance is not nil? Otherwise it could panic further down

2021-08-11 20:06 UTC, rauljordan commented
Ready again @prestonvanloon

2021-08-12 05:04 UTC, prestonvanloon approved these changes

2021-08-12 05:04 UTC, merged