Can re-insert orphaned attestation
prysmaticlabs/prysm pull request #9442
Opened 2021-08-21 17:01 UTC by terencechain

Fixes #9441

This ensures we can re-insert orphaned attestations back to the attestation pool for later inclusion into beacon block. Attestation that is one epoch old will get filtered out

2021-08-23 16:49 UTC, prestonvanloon requested changes
Please add feature flag for testing

2021-08-23 19:32 UTC, prestonvanloon approved these changes

2021-08-23 20:30 UTC, rauljordan commented on beacon-chain/blockchain/head.go
> +		if featureconfig.Get().CorrectlyInsertOrphanedAtts {
Let's move this inside of the saveOrphanedAtts function so that callers dont need to keep track of feature flags

2021-08-23 20:49 UTC, rauljordan approved these changes

2021-08-23 20:50 UTC, rauljordan approved these changes

2021-08-24 01:32 UTC, rauljordan approved these changes

2021-08-24 03:05 UTC, merged