Move Slot and Epoch functions from helpers to core
prysmaticlabs/prysm pull request #9519
Opened 2021-09-02 22:04 UTC by prestonvanloon

**What type of PR is this?**

Other

**What does this PR do? Why is it needed?**

The "helpers" package has become a catch-all for lost functions. This PR moves pure slot and epoch functions that do not require any cache or other dependencies.

**Which issues(s) does this PR fix?**

**Other notes for review**

2021-09-02 22:09 UTC, prestonvanloon commented
Fixing the "core2" imports...

2021-09-03 19:09 UTC, rauljordan submitted a review, later dismissed

2021-09-03 19:11 UTC, rauljordan approved these changes

2021-09-03 19:16 UTC, terencechain requested changes
please fix all `core2` instances

2021-09-03 19:16 UTC, terencechain commented on beacon-chain/blockchain/head_sync_committee_info.go
> +	core2 "github.com/prysmaticlabs/prysm/beacon-chain/core"
core2? Goland auto import failed :(

2021-09-03 19:16 UTC, terencechain commented on beacon-chain/blockchain/process_attestation_helpers.go
> +	core2 "github.com/prysmaticlabs/prysm/beacon-chain/core"
Same here

2021-09-03 20:10 UTC, merged