Rename beacon-chain/core/state to beacon-chain/core/transition pkg
prysmaticlabs/prysm pull request #9530
Opened 2021-09-03 20:00 UTC by prestonvanloon

**What type of PR is this?**

Other

**What does this PR do? Why is it needed?**

General code clean up. We have been aliasing this package to "core" since there are other "state" packages. 

**Which issues(s) does this PR fix?**

None filed.

**Other notes for review**

2021-09-03 20:03 UTC, prestonvanloon commented
Goland renamed a bunch of comments... fixing before requesting review again

2021-09-04 14:43 UTC, rkapka commented on beacon-chain/sync/initial-sync/blocks_fetcher_peers_test.go
> +				if score1 == score {
this change should be reverted

2021-09-04 14:45 UTC, rkapka requested changes
Found a few unwanted changes.

2021-09-04 14:45 UTC, rkapka commented on beacon-chain/sync/initial-sync/blocks_fetcher_peers_test.go
> +				if score1 == score {
This change should be reverted.

2021-09-04 14:45 UTC, rkapka commented on beacon-chain/sync/initial-sync/round_robin_test.go
> +	score := scorer.Score(peer2)
This change should be reverted.

2021-09-04 14:45 UTC, rkapka commented on shared/aggregation/attestations/attestations_test.go
> +			score := scoreAtts(atts)
This change should be reverted.

2021-09-08 10:41 UTC, rkapka approved these changes

2021-09-08 10:41 UTC, merged