Add Altair Metadata Changes
prysmaticlabs/prysm pull request #9552
Opened 2021-09-09 14:27 UTC by nisdas

**What type of PR is this?**

Altair Work

**What does this PR do? Why is it needed?**

- [x] Add in altair metadata rpc changes. This handles the 2 distinct versions of metadata in our node,  we version 
metadata according to the method version. Depending on our method version, we handle the different metadata
types correctly.
- [x] Add in relevant tests.

**Which issues(s) does this PR fix?**

Part of #8638 

**Other notes for review**

2021-09-09 14:50 UTC, rauljordan submitted a review, later dismissed

2021-09-09 15:48 UTC, prestonvanloon requested changes

2021-09-09 15:48 UTC, prestonvanloon commented on beacon-chain/sync/context.go
> +}
Needs unit tests

2021-09-10 02:48 UTC, prestonvanloon submitted a review, later dismissed

2021-09-10 08:10 UTC, rkapka approved these changes

2021-09-10 08:10 UTC, merged