Add Golangci-lint to GitHub Actions and add Deadcode linter
prysmaticlabs/prysm pull request #9597
Opened 2021-09-15 12:39 UTC by estensen

**What type of PR is this?**

Other

**What does this PR do? Why is it needed?**

Improve code quality

**Which issues(s) does this PR fix?**

https://github.com/prysmaticlabs/prysm/issues/9371

**Other notes for review**

One linter at a time will be added at a time instead of adding all the linters all at once to make review easier.

2021-09-15 12:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prysmaticlabs/prysm?pullRequest=9597) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prysmaticlabs/prysm?pullRequest=9597) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prysmaticlabs/prysm?pullRequest=9597) it.</sub>

2021-09-15 13:41 UTC, rkapka commented on beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
> +//nolint:deadcode
We can remove this function.

2021-09-15 14:22 UTC, rkapka requested changes

2021-09-15 14:22 UTC, rkapka commented on .github/workflows/go.yml
> +          args: --print-issued-lines --sort-results --disable-all -E deadcode --skip-dirs=validator/testing --skip-files=validator/web/site_data.go
`validator/testing` has regular code in it, and as such should also be linted.

2021-09-16 08:08 UTC, rkapka submitted a review, later dismissed
Thanks for doing this!

2021-09-16 14:45 UTC, prestonvanloon submitted a review, later dismissed

2021-09-17 09:16 UTC, rkapka approved these changes

2021-09-17 16:37 UTC, rkapka commented
@estensen The `Go / Check` action fails because of a timeout:

> level=error msg="Timeout exceeded: try increasing it by passing --timeout option"

We will have to increase it. I wonder how long it takes. Hopefully not too long. Do you have any data?

2021-09-18 08:12 UTC, estensen commented
@rkapka running it locally on my 16" MacBook Pro after clearing the golangci-lint cache it takes 16 seconds, so I think it will only take slightly more than the default 1m timeout.
I'm increasing the timeout to 15m for now.

2021-09-20 20:17 UTC, rkapka approved these changes

2021-09-21 21:45 UTC, rkapka commented
Hey @estensen , can you please fix conflicts? Thanks!

2021-09-24 14:49 UTC, terencechain approved these changes

2021-09-26 11:11 UTC, rkapka commented
Hey @estensen , can you please redo this?

> Please run bazel run //:gazelle -- fix and commit the BUILD.bazel file(s), otherwise the linter CI check will fail.

I apologize that it takes so long merge this PR.

2021-09-26 19:28 UTC, estensen commented
haha, no worries

2021-09-26 21:29 UTC, rkapka commented
@estensen There are build issues in `beacon-chain/slasher/helpers.go`

2021-09-27 19:08 UTC, rkapka submitted a review, later dismissed

2021-09-27 19:27 UTC, rkapka submitted a review, later dismissed

2021-09-28 09:17 UTC, rkapka commented
`config/params/loader_test.go` has some issues now @estensen

2021-10-01 14:42 UTC, rauljordan commented
Hi @estensen apologies for the delay on this, but you caught us at a difficult time when the codebase is shifting a lot as we are preparing a v2.0.0 release. We are now done with picking our release candidate and your PR wont accumulate as many conflicts as before. Feel free to ping me whenever it's ready again and we'll approve it quickly

2021-10-03 11:46 UTC, estensen commented
@rauljordan haha, this feels like a game of catch-up

PTAL

2021-10-03 14:44 UTC, rkapka approved these changes

2021-10-04 11:06 UTC, merged

2021-10-04 11:06 UTC, rkapka commented
> @rauljordan haha, this feels like a game of catch-up

Congratulations! You've won :-)

2021-10-05 03:56 UTC, prestonvanloon commented
Glad to see this finally merged. Thanks @estensen for your contribution and patience!