finalise deposits before we initialise the node
prysmaticlabs/prysm pull request #9639
Opened 2021-09-21 15:41 UTC by jmozah

**What type of PR is this?**
 Bug fix

**What does this PR do? Why is it needed?**

The PR  finalizes the accumulated deposits before initiazing the node.
when a node pauses for some time and starts again, the deposits to finalize
accumulates. we finalize them here before we are ready to receive a block.
Otherwise, the first few block will not do their duties properly as we will
hold the lock and be busy finalizing the deposits.

**Which issues(s) does this PR fix?**

Fixes #9610 

**Other notes for review**

2021-09-21 15:52 UTC, terencechain commented on beacon-chain/blockchain/service.go
> +			log.WithError(err).Error("Could not insert finalized deposits.")
```suggestion
			log.WithError(err).Error("Could not insert finalized deposits")
```

2021-09-21 15:53 UTC, terencechain commented on beacon-chain/blockchain/service.go
> +		// Otherwise, the first few block will not do their duties properly as we will
```suggestion
		// Otherwise, the first few blocks will be slower to compute as we will
```

2021-09-21 16:40 UTC, rauljordan approved these changes

2021-09-21 22:31 UTC, prestonvanloon requested changes
Please add some kind of regression test for this new logic.

2021-09-22 02:15 UTC, nisdas reviewed
Hey looking at this a bit more, if we insert the finalized deposits here, we will end up doing 3 state fetches during startup. The fetches are expensive because we have to recompute the state from an archived point. It might be more efficient to simply insert it here in `powchain`.
https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/powchain/service.go#L628

We already fetch the finalized state there so we can re-use that when inserting finalized deposits. Also makes this easier to test.

2021-09-24 08:17 UTC, jmozah commented
> Hey looking at this a bit more, if we insert the finalized deposits here, we will end up doing 3 state fetches during startup. The fetches are expensive because we have to recompute the state from an archived point. It might be more efficient to simply insert it here in `powchain`.
> https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/powchain/service.go#L618
> 
> We already fetch the finalized state there so we can re-use that when inserting finalized deposits. Also makes this easier to test.

@nisdas I considered doing it there first as we load the caches there.
There are two problems with doing it there (infact loading caches too has a problem now).

1) The system should not send `state.Initialized` before we have 
     - loaded all the cache
     - Finalised all of the caches. (this is the current problem though)
    This can be controlled only in blockchain.service.
    
 2) We don't have access to

2021-09-27 11:17 UTC, nisdas approved these changes

2021-09-28 08:03 UTC, nisdas commented
@prestonvanloon , ping on another review for the PR.

2021-09-29 15:02 UTC, prestonvanloon approved these changes

2021-09-29 15:43 UTC, merged